### ISSUE TITLE
[Bug] : Merging properties and rules with custom properties results in wrong border

### ISSUE THREAD

**Issue by hatsumatsu** [cssnano/cssnano#1000]
**Describe the bug**

Using short and long formats for border properties AND custom properties results wrong border rule. Seems related to but different from https://github.com/cssnano/cssnano/issues/864

**To Reproduce**

1. Use this CSS in the playground:

```css
:root {
	--border--width--thick: 10px;
}

.a {

/**
 * works without custom properties:
 * border-top: 10px solid blue;    
 */
    border-top: var(--border--width--thick) solid blue;    
    border-width: 1px;    
}

.a > .b {
	/**
     * works without custom properties:
	 * border-left: 10px solid blue;    
	 */
    border-left: var(--border--width--thick) solid blue;
    border-width: 1px;
}	
```
2. The result is: 

```css
:root{--border--width--thick:10px}.a{border-top:solid #00f}.a,.a>.b{border-width:1px}.a>.b{border-left:solid #00f}
```

3. See how `.b` should have a border width of 1px. Instead `border-left:solid #00f` is produced which falls back to a width of `medium`.

**Expected behavior**
Border rules width custom properties should be megred correctly.

**Desktop (please complete the following information):**
- CSSNANO Version 4.1.10
-   `{"preset" : "default"}`

**Additional context**
This bug occured using [nextjs](https://github.com/vercel/next.js) in which configuration to cssnano is not exposed. Looks like a broad user base is affected by this bug.

**Comment by ludofischer** [comment]
Confirmed with 5.0.0-rc.2

**Comment by ludofischer** [comment]
The specific error (with disappearance of the `var()`) seems to come from the between merge-rules and another plugin, since it does not reproduce with merge-rules alone. But I think the merge rules output is still wrong:
```css
.a { border-top:·var(--border-width-thick) solid blue; }
.a, .a > .b { border-width: 1px; }
.a > .b {border-left: var(--border-width-thick) solid blue; }

```
`border-left` on `.a > .b`  is now 10px when originally it was 1px.
