### ISSUE TITLE
[Bug] : merge border rule encountered an error

### ISSUE THREAD

**Issue by commyfriend** [cssnano/cssnano#1003]
**Describe the bug**
when use cssnano to minify the css code below，it throw error like this。
```sh
TypeError: Cannot read property 'toLowerCase' of undefined
    at /Volumes/ssd/tmp/cssnano/bug.css:1:1
    at /Volumes/ssd/tmp/cssnano/bug.css:4:3
    at /Volumes/ssd/tmp/cssnano/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:632:214
    at mergeRules (/Volumes/ssd/tmp/cssnano/node_modules/postcss-merge-longhand/dist/lib/mergeRules.js:53:17)
    at /Volumes/ssd/tmp/cssnano/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:625:38
    at Array.forEach (<anonymous>)
    at /Volumes/ssd/tmp/cssnano/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:622:13
    at /Volumes/ssd/tmp/cssnano/node_modules/postcss/lib/container.js:98:18
    at /Volumes/ssd/tmp/cssnano/node_modules/postcss/lib/container.js:74:18
    at Rule.each (/Volumes/ssd/tmp/cssnano/node_modules/postcss/lib/container.js:60:16)
    at Rule.walk (/Volumes/ssd/tmp/cssnano/node_modules/postcss/lib/container.js:71:17)
    at Rule.walkDecls (/Volumes/ssd/tmp/cssnano/node_modules/postcss/lib/container.js:96:19) {
```
**To Reproduce**
css code
```css
.test {
  border-style: solid;
  border-bottom-width: 1px;
  border-bottom-color: rgb(196, 196, 196);
  border-top-style: none;
  border-right-style: none;
  border-left-style: none;
}
```

postcss.config.js
```js
module.exports = {
  plugins: [
      require('cssnano')({
          preset: 'default',
      }),
  ],
};
```

**Expected behavior**
no error be thrown

**Desktop (please complete the following information):**
- CSSNANO Version 7.0.35
