### ISSUE TITLE
[Bug] : Error border style generated

### ISSUE THREAD

**Issue by so-diao** [cssnano/cssnano#1006]
**Describe the bug**
Multiple border style were merged into `invalid property value`.
`border: 0 inherit;` = `invalid property value`.

**To Reproduce**
```js
cssnano({
    preset: ['default', {
        discardComments: {
            removeAll: true,
        },
    }]
})
```
```css
table tbody, table tr {
    border-color: inherit;
    border-style: inherit;
    border-width: 0;
}
-----------result------------
table tbody,table tr {
    border: 0 inherit;
    border-color: inherit
}
```

**Screenshots**
![图片](https://user-images.githubusercontent.com/24741025/109937252-acab0980-7d09-11eb-8ad4-b0b7f5142ea9.png)

**Expected behavior**
Is there any way to exclude code?
↓↓↓↓↓↓↓↓↓↓↓↓↓↓
```css
/* cssnano-exclude */
table tbody, table tr {
    border-color: inherit;
    border-style: inherit;
    border-width: 0;
}
/* cssnano-end */
```

**Desktop (please complete the following information):**
```
"cssnano": "^4.1.10"
"postcss": "^7.0.29"
```
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 AMD Athlon(tm) X4 860K Quad Core Processor
    Memory: 5.97 GB / 11.95 GB
    Node: 14.14.0 - D:\app\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - D:\app\nodejs\npm.CMD
  Utilities:
    Git: 2.20.1.
  IDEs:
    VSCode: 1.52.1 - D:\app\Microsoft VS Code\bin\code.CMD
  Browsers:
    Internet Explorer: 11.0.19041.1

`-- cssnano@4.1.10  -> D:\app\XXXX\build\node_modules\_cssnano@4.1.10@cssnano
```
