### ISSUE TITLE
[Bug] : postcss-colormin produces odd results for #rrggbbaa input

### ISSUE THREAD

**Issue by silverwind** [cssnano/cssnano#1042]
Using `postcss-colormin@4.0.3`:

Original:
```css
:root {
 --color-light:#00000004;
 --color-light-border:#0000001d;
 --color-hover:#0000000f;
 --color-active:#00000014;
}
```

After colormin:
```css
:root {
  --color-light:rgba(0,0,0,0.01568627450980392);
  --color-light-border:rgba(0,0,0,0.11372549019607843);
  --color-hover:rgba(0,0,0,0.058823529411764705);
  --color-active:rgba(0,0,0,0.0784313725490196);
}
```

I think in this case, `colormin` should not touch the original color because it is already pretty minimal.
