### ISSUE TITLE
[Bug] : svgo

### ISSUE THREAD

**Issue by jonnitto** [cssnano/cssnano#1049]
**Describe the bug**
Since cssnano V5, I'll get this error warning

**To Reproduce**
Run CSS Nano

```
⚠  Error in parsing SVG: Text data outside of root node.
Line: 0
Column: 553
Char: # [postcss-svgo]
```

**Expected behavior**
No error in parsing SVG

**Desktop:**
- CSSNANO Version 5.0.1
- Preset: `default`

`npx envinfo`

```
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 265.01 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    Composer: 2.0.9 - /usr/local/bin/composer
    Homebrew: 3.0.2 - /usr/local/bin/brew
    pip3: 21.0.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.28.0 - /usr/local/bin/git
    Clang: 12.0.0 - /usr/bin/clang
    Mercurial: 5.5.1 - /usr/local/bin/hg
  Servers:
    Apache: 2.4.46 - /usr/local/bin/apachectl
    Nginx: 1.19.2 - /usr/local/bin/nginx
  Virtualization:
    Docker: 20.10.5 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    PhpStorm: 2020.2.2
    VSCode: 1.55.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.28.2 - /usr/bin/perl
    PHP: 7.4.15 - /usr/local/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.2 - /usr/local/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    MySQL: 10.3.28 (MariaDB) - /usr/local/opt/mariadb@10.3/bin/mysql
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 81.1.8.86
    Chrome: 89.0.4389.128
    Chrome Canary: 92.0.4476.0
    Edge: 89.0.774.76
    Firefox: 81.0.1
    Firefox Developer Edition: 76.0
    Safari: 14.0.3
    Safari Technology Preview: 14.2
```

`npm ls cssnano`

```
├── cssnano@5.0.1
└─┬ rollup-plugin-postcss@4.0.0
  └── cssnano@4.1.11
```

`minimze` in ` rollup-plugin-postcss` is disabled

**Comment by ludofischer** [comment]
I can't say if the issue is in cssnano or svgo. Can you link to a repository with a minimal reproduction? Or try running `svgo` directly on the problematic SVG and see if it gives a warning. Does cssnano output the minified css or does it crash in the middle? We've had a similar issue with too SVGO many warnings that should have been fixed: https://github.com/cssnano/cssnano/issues/1040

**Comment by internalsystemerror** [comment]
Using `@fortawesome/fontawesome-free` I am able to reproduce this error:

Works:
```scss
//
// Import font awesome styles
//
@import "~@fortawesome/fontawesome-free/scss/fontawesome";
//@import "~@fortawesome/fontawesome-free/scss/regular";
//@import "~@fortawesome/fontawesome-free/scss/solid";
@import "~@fortawesome/fontawesome-free/scss/brands";
```

Fails:
```scss
//
// Import font awesome styles
//
@import "~@fortawesome/fontawesome-free/scss/fontawesome";
@import "~@fortawesome/fontawesome-free/scss/regular";
//@import "~@fortawesome/fontawesome-free/scss/solid";
@import "~@fortawesome/fontawesome-free/scss/brands";
```

**Comment by alexander-akait** [comment]
@internalsystemerror What is the error?

**Comment by internalsystemerror** [comment]
same as the OP `Error in parsing SVG: Text data outside of root node.`. There are other SVGs being inlined which don't throw this error, there is something specific about the SVG included in `regular.scss` and I'm trying to figure out what exactly. I don't believe its because the SVG itself is invalid, though that may of course be a possibility.

**Comment by alexander-akait** [comment]
Can you show `regular.scss` code, looks like SVG invalid itself or bug in svgo, also can you provide version of `cssnano`?

**Comment by internalsystemerror** [comment]
cssnano v5.0.5

I'll share what I can now but I'll have to get back with the specific generated css on Monday. Note, that the `brands.scss` also includes an SVG which is being inlined without throwing an error.

From: https://github.com/FortAwesome/Font-Awesome/blob/5.15.3/scss/regular.scss

```scss
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 400;
  font-display: $fa-font-display;
  src: url('#{$fa-font-path}/fa-regular-400.eot');
  src: url('#{$fa-font-path}/fa-regular-400.eot?#iefix') format('embedded-opentype'),
  url('#{$fa-font-path}/fa-regular-400.woff2') format('woff2'),
  url('#{$fa-font-path}/fa-regular-400.woff') format('woff'),
  url('#{$fa-font-path}/fa-regular-400.ttf') format('truetype'),
  url('#{$fa-font-path}/fa-regular-400.svg#fontawesome') format('svg');
}
```

And the SVG being inlined: https://github.com/FortAwesome/Font-Awesome/blob/5.15.3/webfonts/fa-regular-400.svg
