### ISSUE TITLE
[Bug] : mergeLonghand should not apply to CSS variables

### ISSUE THREAD

**Issue by redallen** [cssnano/cssnano#1051]
**Describe the bug**
mergeLonghand should not apply to CSS `var`s since it cannot know what the var expands to.

**To Reproduce**
Input:
```css
.pf-c-select__toggle::before {
    border-color: var(--pf-c-select__toggle--before--BorderTopColor) var(--pf-c-select__toggle--before--BorderRightColor) var(--pf-c-select__toggle--before--BorderBottomColor) var(--pf-c-select__toggle--before--BorderLeftColor);
    border-style: solid;
    border-width: var(--pf-c-select__toggle--before--BorderWidth);
}
```

Output:
```css
.pf-c-select__toggle:before{
  border-left:var(--pf-c-select__toggle--before--BorderWidth) solid var(--pf-c-select__toggle--before--BorderLeftColor);
  border-bottom:var(--pf-c-select__toggle--before--BorderWidth) solid var(--pf-c-select__toggle--before--BorderBottomColor);
  border-right:var(--pf-c-select__toggle--before--BorderWidth) solid var(--pf-c-select__toggle--before--BorderRightColor);
  border-top:var(--pf-c-select__toggle--before--BorderWidth) solid var(--pf-c-select__toggle--before--BorderTopColor)
}
```

**Expected behavior**
Expected output: Same as input.

`cssnano@4.1.10`
