### ISSUE TITLE
[Bug] : The default preset breaks border related styles by `cssDeclarationSorter`

### ISSUE THREAD

**Issue by naruaway** [cssnano/cssnano#1054]
**Describe the bug**
The latest version of [`cssnano`](https://github.com/cssnano/cssnano/) (`5.0.1`) 's default preset breaks border related styles by `cssDeclarationSorter`.

**To Reproduce**
Please take a look at [the minimum reproducible example](https://github.com/naruaway/cssnano-border-declaration-sorter-bug).

**Expected behavior**
```css
.border-top-test {
  border-color: purple;
  border-top-width: 1px;
  border-top-style: solid;
}
```
should not be broken by `cssnano`'s default preset.
Currently the output is 
```css
.border-top-test {
  border-color: purple;
  border-top: 1px solid;
}
```
and the top border color is no longer `purple`.

**Additional info**
- CSSNANO Version: `5.0.1`
- Plugins/presets versions: `cssnano-preset-default@5.0.0`
- It is reproducible in several environments including Linux and macOS
