### ISSUE TITLE
[Bug] : TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by stagefright5** [cssnano/cssnano#1102]
**Describe the bug**

I have an angular project (latest v11, more precisely `"@angular-devkit/build-angular": "0.1102.13"`) that I am trying to build (`ng build --configuration=production`) and this package is throwing the following error.

<pre><code>
[error] TypeError: Cannot read property 'toLowerCase' of undefined
    at $PROJECT_ROOT\styles.a7990a61a7ecede859a2.css:3506:1
    at hasInherit ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\canMerge.js:16:39)
    at Array.some (<anonymous>)
    at _default ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\canMerge.js:23:13)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:234:33
    at mergeRules ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\mergeRules.js:44:11)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:233:29
    at Array.forEach (<anonymous>)
    at Object.merge ($PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\lib\decl\borders.js:231:7)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\index.js:20:13
    at Array.forEach (<anonymous>)
    at $PROJECT_ROOT\node_modules\postcss-merge-longhand\dist\index.js:18:23
    at $PROJECT_ROOT\node_modules\postcss\lib\container.js:115:18
    at $PROJECT_ROOT\node_modules\postcss\lib\container.js:74:18
    at Root.each ($PROJECT_ROOT\node_modules\postcss\lib\container.js:60:16)
    at Root.walk ($PROJECT_ROOT\node_modules\postcss\lib\container.js:71:17)
    at Root.walkRules ($PROJECT_ROOT\node_modules\postcss\lib\container.js:113:19)
</code></pre>

Also, this issue occurs in scss rules where there is a usage of mixins with hashmap variable:

```scss
@import "mixins";

// styles.scss

.properties-header-container {
    @include themify($themes) {
        border-color: themed("medium_gray") !important;
    }
}
```
And the mixins defined here

```scss
// mixins.scss
@import "variables";

$theme-map: null;

@mixin themify($themes) {
    @each $theme, $map in $themes {
        .theme-#{$theme} & {
            $theme-map: () !global;

            @each $key, $submap in $map {
                $value: map-get(map-get($themes, $theme), '#{$key}');
                $theme-map: map-merge(
                    $theme-map,
                    (
                        $key: $value,
                    )
                ) !global;
            }

            @content;
            $theme-map: null !global;
        }
    }
}

@function themed($key) {
    @return map-get($theme-map, $key);
}
```

and variables defined here:

```scss
// variables.scss
$white_color: #1c1c1c;
$lighter_gray: #d3d3d3;
$medium_gray: #b6b2b2;
$preview_gray: #7b7f8b;
/*
etc...
*/
```

The generated css equivaent was something like this:
```scss
// styles.a7990a61a7ecede859a2.scss

.properties-header-container {
    border-color: !important;
}
```
NOTICE: You can notice the `border-color` does not have any color value.

**To Reproduce**
1. Run `ng build --configuration=production` in an angular@11 app with above scss 

**Expected behavior**
The css should have been generated like this:
```scss
// styles.a7990a61a7ecede859a2.scss

.properties-header-container {
    border-color: #b6b2b2 !important;
}
```

**Desktop (please complete the following information):**
- CSSNANO Version - 5.0.2
- Plugins/presets versions - No Idea
- Add the output of `npx envinfo && npm ls cssnano`
```sh
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 13.28 GB / 23.85 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Cargo: 1.40.0 - ~\.cargo\bin\cargo.EXE
    Gradle: 6.4 - C:\Program Files\Gradle\gradle-6.4\bin\gradle.BAT
    pip3: 20.2.3 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    Git: 2.29.2. - C:\Program Files\Git\cmd\git.EXE
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    VSCode: 1.56.2 - C:\Users\sanka\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.23 - C:\Windows\system32\bash.EXE
    Java: 1.8.0_251 - C:\Program Files\Java\jdk1.8.0_251\bin\javac.EXE
    Python: 3.9.1 - C:\Python39\python.EXE
    Python3: 3.9.5
    Rust: 1.40.0 - C:\Users\sanka\.cargo\bin\rustc.EXE
  Databases:
    PostgreSQL: 12.3 - C:\Program Files\PostgreSQL\12\bin\postgres.EXE
    SQLite: 3.28.0 - C:\Users\sanka\AppData\Local\Android\Sdk\platform-tools\sqlite3.EXE
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.56)
    Internet Explorer: 11.0.19041.1

n-studio@7.8.0 D:\work\bhive-ad
`-- @angular-devkit/build-angular@0.1102.13
  `-- cssnano@5.0.2
```

**Additional context**
- Using this in a project of LATEST `angular@11`
- This issue does not exist in `@angular/cli@11.2.9` (with `"@angular-devkit/build-angular": "0.1102.9"`) which had `cssnano@4.1.11` as the dependency
- For tracking https://github.com/angular/angular-cli/issues/20673

**Comment by ludofischer** [comment]
Thank you for the bug report. Can you post some how the unminified CSS output (after sass has run but before minification)? It woud help us to pinpoint which rule is causing this error. As a workaround you can try disabling the `merge-longhand` when cssnano gets added to the PostCSS configuration.

```javascript
cssnano({mergeLonghand: false})
```
Unfortunately I am not familiar with Angular Cli so I don't know you can access the PostCSS configuration.

I think the failing line in `canMerge.js` is

```
const hasInherit = node => node.value.toLowerCase() === 'inherit';
```
which I find strange, because how can the node not have a value?

**Comment by stagefright5** [comment]
@ludofischer , as I have mentioned in the op, the generated css is this. Please observe that the `border-color` property DOES NOT have any hex code mentioned for color.
```scss
// styles.a7990a61a7ecede859a2.scss

.properties-header-container {
    border-color: !important;
}
```

It seems like the variable which value was supposed to get replaced, had been replaced with an empty string.
