### ISSUE TITLE
pack same CSS media query rules into one media query rule

### ISSUE THREAD

**Issue by evilebottnawi** [cssnano/cssnano#111]
``` css
.foo {
  width: 10px;
}

@media (min-width: 640px) {
  .foo {
    width: 150px;
  }
}

.bar {
  width: 20px;
}

@media (min-width: 320px) {
  .bar {
    width: 200px;
  }
}

@media (min-width: 640px) {
  .bar {
    width: 300px;
  }
}
```

Output:

``` css
.foo{width:10px}@media (min-width:640px){.foo{width:150px}}.bar{width:20px}@media (min-width:320px){.bar{width:200px}}@media (min-width:640px){.bar{width:300px}}
```

But we can merge `@media (min-width:640px)`. https://github.com/hail2u/node-css-mqpacker he knows how to do it. Maybe add it to the kernel, or to implement the same behavior in one of the plugins. Also pay attention to the option sort.

**Comment by ben-eb** [comment]
This has been wanted for a while. Hopefully we can look into this for v4.

https://github.com/ben-eb/cssnano/issues/49#issuecomment-137680616

**Comment by faddee** [comment]
It would be really cool if it also could optimize media queries, if you were nesting them using SASS.

E.g.

```sass
@mixin gutter {
  margin-right: 1rem;

  @media (min-width: 320px) {
    margin-right: 2rem;
  }
}

.column {
  @media (min-width: 768px) {
    @include gutter;
  }
}

// Compiles to:

@media (min-width: 768px) {
  .column {
    margin-right: 1rem;
  }
}

@media (min-width: 768px) and (min-width: 320px) {
  .column {
    margin-right: 2rem;
  }
}
```

In this case, the only part necessary here would be: 

```sass
@media (min-width: 768px) {
  .column {
    margin-right: 2rem;
  }
}
```

I understand this is hard to implement and needs a lot of testing. But I haven't found anything like this anywhere so it would be a killer.

**Comment by DylanPiercey** [comment]
Why not use https://github.com/hail2u/node-css-mqpacker?

**Comment by Spekachu** [comment]
I built a tool that merges media queries: http://www.spekachu.com/css-media-query-merger/

**Comment by ausi** [comment]
I think this optimization could be problematic in some cases. If in your example an element has both classes `foo` and `bar` the styling would change if the two `@media (min-width: 640px)` get merged.

**Comment by soluml** [comment]
In addition to media queries, I think it'd be great to be able to merge `@supports` rules as well!

**Comment by iandevlin** [comment]
@soluml `cssnano` appears to already do this, and I wish it didn't as it is breaking something I am currently working on. I would like to be able to turn off `mergeRules` for `@supports`.

**Comment by dutchenkoOleg** [comment]
https://github.com/hail2u/node-css-mqpacker

and I can offer
https://github.com/dutchenkoOleg/sort-css-media-queries

**Comment by andyjansson** [comment]
@iandevlin got a failing test case?

**Comment by iandevlin** [comment]
@andyjansson I had, and now I cannot find it. I will update once I find it again.

**Comment by chriseppstein** [comment]
Merging the two `(min-width: 640px)` media queries will break an element having `class="foo bar"` for widths between `320px` and `640px`.

I've recently changed cssnano's policy to reject unsafe optimizations going forward. See this issue for more information: https://github.com/ben-eb/cssnano/issues/424

**Comment by evilebottnawi** [comment]
It can be safe in many cases. Example:
```css
@media print{
  h1{
    display:block
  }
}
@media print{
  h1{
    color:red
  }
  h2{
    padding:10px
  }
}
```

Also i can provide more examples
