### ISSUE TITLE
[Bug] : PropConflict when using postcss-merge-rules

### ISSUE THREAD

**Issue by codeonquer** [cssnano/cssnano#1112]
Always forgive my poor English.

## Describe the bug

- postcss-merge-rules@5.0.0

My origin scss file:

- displayFlexCover comes from somewhere, I place them together;
- I place some useless props in displayFlexCover to generate merge-rules.

```scss
@mixin displayFlexCover () {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  -webkit-justify-content: center;
}

.fa-csr-bg {
  .table {
    @include displayFlexCover;
    justify-content: flex-start;
  }

  .table2 {
    @include displayFlexCover;
  }
}
```

after scss:

```css
.fa-csr-bg .table {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  -webkit-justify-content: center;
  justify-content: flex-start;
}
.fa-csr-bg .table2 {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  -webkit-justify-content: center;
}
```

after postcss-merge-rules:

```css
.fa-csr-bg .table {
  -webkit-justify-content: center;
  justify-content: flex-start;
}
.fa-csr-bg .table,.fa-csr-bg .table2 {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.fa-csr-bg .table2 {
  -webkit-justify-content: center;
}
```

Now, we can see that `justify-content` in `.fa-csr-bg .table` is in conflict. I want `flex-start`, but `center` has higher priorit.

## Find the key

I find that postcss-merge-rules is 5.0.1 now, so I use this version describe my discovery.

```js
// cssnano/packages/postcss-merge-rules/src/index.js
208  intersection = intersection.filter((decl, intersectIndex) => {
209    const index = indexOfDeclaration(firstDecls, decl);
210    const nextConflictInFirst = firstDecls
211      .slice(index + 1)
212      .find((d) => isConflictingProp(d.prop, decl.prop));
213    if (!nextConflictInFirst) {
214      return true;
215    }
216    const nextConflictInIntersection = intersection
217      .slice(intersectIndex + 1)
218      .find((d) => isConflictingProp(d.prop, decl.prop));
219    if (!nextConflictInIntersection) {
220      return false;
221    }
222    if (declarationIsEqual(nextConflictInFirst, nextConflictInIntersection)) {
223      return true;
224    }
225    return false;
226  });

...

262 second.parent.insertBefore(second, receivingBlock);
```

when `justify-content` in intersection (includs `justify-content` and `-webkit-justify-content`) finds its nextConflictInFirst, it gets `-webkit-justify-content` and satisfies its nextConflictInIntersection condition. `justify-content` in intersection is keeped. But we never compare it with second `justify-content` in firstDecls.

`-webkit-justify-content` in intersection is not keeped as expected.

Then we insert `justify-content` in intersection before second after first. 

Now `center` covers `flex-start`.

To solve the problem, we can

- Don't use Array.find function in line 212. We need to compare to the end of props in firstDecls one by one.
- Don't insertBefore second in line 262. We can insertBefore first. This maybe causes other problems because we only compare after indexOfDeclaration.

## Additional

I don't know if I find the correct way. Hope to get a response.
