### ISSUE TITLE
[Bug] postcss-colormin@5.1.0 incorrectly minifies numbers as colors

### ISSUE THREAD

**Issue by jbms** [cssnano/cssnano#1117]
Example CSS file:
```css
a {
  --my-var: 232;
}
```

Postcss config:

```
module.exports = {
    plugins: [
        require('cssnano')({
            plugins: [
                "postcss-colormin",
            ],
        }),
    ],
};
```

Incorrect minified result with postcss-colormin@5.1.0:

```css
a {
  --my-var: #232;
}
```

Correct minified result with postcss-colormin@5.0.0:

```css
a {
  --my-var: 232;
}
```
