### ISSUE TITLE
[Bug] : `mergeLonghand` plugin removes fallbacks for older browsers

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [cssnano/cssnano#1163]
**Describe the bug**
Our project still needs to support IE11, so we use a browserslist that includes it. However when we tried to use cssnano, we noticed that it removes fallback css needed for IE11! The culprit turns out to be the seemingly innocuous `mergeLonghand` plugin.

**To Reproduce**
Using the default preset, disable every optimization except `mergeLonghand` and optimize the following css:
```css
.my-class {
  margin-right: 22px;
  margin-right: max(4%, 22px);
}
```
The css is transformed to
```css
.my-class {
  margin-right: max(4%, 22px);
}
```

**Expected behavior**
The `margin-right: 22px;` fallback is not removed.

**Desktop (please complete the following information):**
- node 14.17.3
- postcss 8.3.5
- cssnano 5.0.6

**Additional context**
This problem was also noted in #935 but the issue was closed before the problem was identified. There's nothing in the description for `mergeLonghand` to suggest that this behavior is intended (and if it is, IMO it shouldn't be part of the default preset's "safe" optimizations).
