### ISSUE TITLE
[Bug]: `orderedValues` drops some function calls

### ISSUE THREAD

**Issue by loilo** [cssnano/cssnano#1202]
### Describe the bug

Having the `orderedValues` option enabled (as the `default` preset does) will drop the `min()` call in the following rule:

```css
.selector {
  border-left: min(10px, 1vw) solid red;
}
```

This produces the following output:

```css
.selector{border-left:solid red}
```

### Expected behaviour

The `min()` call should be kept.

### Steps to reproduce

Follow the steps in the reproduction readme at [`loilo/repro-cssnano-orderedvalues`](https://github.com/loilo/repro-cssnano-orderedvalues).

### Version

5.0.8

### Preset

default

### Environment

```shell
System:
  OS: macOS 11.3.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 751.55 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
```

### Package details

```shell
├── cssnano@5.0.8 
└── postcss@8.3.9
```
