### ISSUE TITLE
[Bug]: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ClarkXia** [cssnano/cssnano#1217]
### Describe the bug

failed with Css Minimizer plugin when write css code like: 

```css
.next-step-arrow[dir='rtl'] .next-step-item:before {
  border: 16px solid transparent;
  border: var(--step-arrow-item-border-width, 16px) solid transparent;
  border-right-color: transparent;
}
```

when `diff` get empty array, `prop` will get undefined

https://github.com/cssnano/cssnano/blob/8bb7ba6c1733fd12122589169d847b1a1212a6b5/packages/postcss-merge-longhand/src/lib/decl/borders.js#L90-L94

### Expected behaviour

compiled successfuly

### Steps to reproduce

1. use css-minimizer-webpack-plugin as css minimizer
2. write css code like 
```css
.next-step-arrow[dir='rtl'] .next-step-item:before {
  border: 16px solid transparent;
  border: var(--step-arrow-item-border-width, 16px) solid transparent;
  border-right-color: transparent;
}
```

### Version

5.0.6

### Preset

default

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 221.75 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
```

### Package details

```shell
├── cssnano@5.0.6
└── postcss@8.3.5
```
