### ISSUE TITLE
[Feature Request]: `preserve` option for `postcss-normalize-display-values`

### ISSUE THREAD

**Issue by Antonio-Laguna** [cssnano/cssnano#1277]
### What should be improved?

Adding a `preserve` option to `postcss-normalize-display-values`

### Describe the solution you would like

With this option the transform would work as follows:

```css
div {
    display: inline flow-root
}
```

To:

```css
div {
    display: inline flow-root;
    display: inline-block;
}
```

### Additional context

After picking up development on postcss-preset-env I came across this issue: https://github.com/csstools/postcss-plugins/issues/112 and would love to add this plugin there. However to keep it consistent with other plugins we'd like to add `preserve` to keep both options. I

### Are you willing to work on this?

- [X] Yes, I would like to help
