### ISSUE TITLE
[Bug]: CSS custom properties in @supports cannot remove spaces

### ISSUE THREAD

**Issue by yisibl** [cssnano/cssnano#1330]
### Describe the bug

```css
@supports (--foo:    ) {
      html { background: green; }
}
```

### Expected behaviour

Browser page shows green background.
After compression, keep at least one space after `--foo: `, otherwise not valid in Chrome.

See also: https://lea.verou.me/2020/10/the-var-space-hack-to-toggle-multiple-values-with-one-custom-property/

```css
@supports (--foo: ){html{background:green}}
```

### Steps to reproduce

https://cssnano.co/playground/#eyJpbnB1dCI6IkBzdXBwb3J0cyAoLS1mb286ICAgICkge1xuICAgICAgaHRtbCB7IGJhY2tncm91bmQ6IGdyZWVuOyB9XG59IiwiY29uZmlnIjoiY3NzbmFuby1wcmVzZXQtZGVmYXVsdCJ9

### Version

5.0

### Preset

default

### Environment

```shell
/
```

### Package details

```shell
/
```
