### ISSUE TITLE
[Bug]: invalid border shorthand with custom properties

### ISSUE THREAD

**Issue by stefanprobst** [cssnano/cssnano#1354]
### Describe the bug

the following:

```css
h1 {
  --width: 8px 2px;
  border-width: var(--width);
  border-style: solid;
  border-color: hotpink;
}
```

results in (default preset):

```css
h1{--width:8px 2px;border:var(--width) solid hotpink}
```

which is invalid.

### Expected behaviour

when a custom property is encountered, don't collapse border properties into shorthand.

### Steps to reproduce

1. paste the above snippet in the cssnano playground
2. click minimize

### Version

whatever is currently on the cssnano playground, 5.1.0 probably

### Preset

default

### Environment

```shell
System:
    OS: Linux 5.13 KDE neon 5.24
    CPU: (4) x64 Intel(R) Core(TM) i5-6400T CPU @ 2.20GHz
    Memory: 19.96 GB / 31.30 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Package details

```shell
=> Found "postcss@8.4.5"
```
