### ISSUE TITLE
[Bug]: long css class names prevent from creating common rule

### ISSUE THREAD

**Issue by bloody-ux** [cssnano/cssnano#1370]
### Describe the bug

I have below input css, after running with cssnano in https://cssnano.co/playground/. `background-position, background-repeat, background-size` don't get extracted to common rule. 

``` css
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_a {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 2vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_b {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 3vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_c {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 4vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_d {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 5vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_e {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 6vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_f {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 7vw
}

```

### expected result

``` css
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_a,
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_b,
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_c,
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_d,
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_e,
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_f {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_a {
  height: 2vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_b {
  height: 3vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_c {
  height: 4vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_d {
  height: 5vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_e {
  height: 6vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_f {
  height: 7vw
}

```

### actual result

``` css
.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_a {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 2vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_b {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 3vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_c {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 4vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_d {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 5vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_e {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 6vw
}

.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_f {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 7vw
}

```

### Steps to reproduce

1. open https://cssnano.co/playground/
2. paste below code to input field.
3. click 'Save'

### Version

latest

### Preset

default

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 65.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
```

### Package details

```shell
Run with https://cssnano.co/playground/
```
