### ISSUE TITLE
[Bug]: common rules don't get merged correctly

### ISSUE THREAD

**Issue by bloody-ux** [cssnano/cssnano#1371]
### Describe the bug

After below input is optimized with cssnano, duplicate rules still exist.

``` css
._a {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 2vw
}

._b {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 3vw
}

._c {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 4vw
}

._d {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 5vw
}

._e {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 6vw
}

._f {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain;
  height: 7vw
}

```

### expected result

``` css
._a,
._b,
._c,
._d,
._e,
._f {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain
}

._a {
  height: 2vw
}


._b {
  height: 3vw
}

._c {
  height: 4vw
}

._d {
  height: 5vw
}

._e {
  height: 6vw
}

._f {
  height: 7vw
}

```

### actual result
``` css
._a {
  height: 2vw
}

._a,
._b {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain
}

._b {
  height: 3vw
}

._c {
  height: 4vw
}

._c,
._d {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain
}

._d {
  height: 5vw
}

._e {
  height: 6vw
}

._e,
._f {
  background-position: 50%;
  background-repeat: no-repeat;
  background-size: contain
}

._f {
  height: 7vw
}

```

### Steps to reproduce

1. Open https://cssnano.co/playground/
2. paste above input to input field.
3. click 'Minimize'

### Version

latest

### Preset

default

### Environment

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 65.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
```

### Package details

```shell
https://cssnano.co/playground/
```
