### ISSUE TITLE
[Bug]: Invalid CSS is produced for `:where(a, :not(a))` selectors

### ISSUE THREAD

**Issue by romainmenke** [cssnano/cssnano#1402]
### Describe the bug

Minification of `:where` with twice the same class, one of which nested in `:not` has unexpected results

Input : 

```css
:where(a, :not(a)) {
  any: style;
}
```

Output :

```css
:where(a,:not){any:style}
```

--------

Input : 

```css
:where(a, :not(b)) {
  any: style;
}
```

Output :

```css
:where(a,:not(b)){any:style}
```

### Expected behaviour

Expected `:not()` to always be a pseudo class function after minification.

### Steps to reproduce

https://cssnano.co/playground/#eyJpbnB1dCI6Ijp3aGVyZShhLCA6bm90KGEpKSB7XG4gIGFueTogc3R5bGU7XG59IiwiY29uZmlnIjoiY3NzbmFuby1wcmVzZXQtZGVmYXVsdCJ9

<img width="1440" alt="Screenshot 2022-05-28 at 18 15 38" src="https://user-images.githubusercontent.com/11521496/170833727-238b7223-3b9a-45a3-ba40-e64ba2a70e61.png">

Disabling `minifySelectors` makes the issue go away, so this seems to be the source.

### Version

5.0.8

### Preset

default

### Environment

```shell
Any env fails
```

### Package details

```shell
+-- cssnano@5.0.8
```
