### ISSUE TITLE
[Bug]: mergeRules invalid order of selectors

### ISSUE THREAD

**Issue by PRR24** [cssnano/cssnano#1424]
### Describe the bug

if mergeRules is enabled, it may result invalid order of selectors

### Expected behaviour

Order of selectors does not change the behaviour of initial css file

### Steps to reproduce

source:
```css
.name {
  font-family: "InterVariable", "Inter", BlinkMacSystemFont, -apple-system, "Segoe UI", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  font-weight: 400;
  font-size: 18px;
  line-height: 1.5;
  letter-spacing: -0.01em;
  -webkit-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
  -moz-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
  font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
  font-weight: 600;
}
.name.small {
  font-family: "InterVariable", "Inter", BlinkMacSystemFont, -apple-system, "Segoe UI", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
  font-weight: 400;
  font-size: 16px;
  line-height: 1.5;
  letter-spacing: -0.01em;
  -webkit-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
  -moz-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
  font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
  font-weight: 600;
}
```
Result with "default" preset (prettified for readability):
```css
.name {
    -webkit-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
    -moz-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
    font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
    font-size: 18px;
    font-weight: 600
}
.name, .name.small {
    font-family: InterVariable, Inter, BlinkMacSystemFont, -apple-system, Segoe UI, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol;
    font-weight: 400;
    letter-spacing: -.01em;
    line-height: 1.5
}
.name.small {
    -webkit-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
    -moz-font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
    font-feature-settings: "ccmp", "locl", "mark", "kern", "pnum", "cpsp";
    font-size: 16px;
    font-weight: 600
}
```
Result causes .name to end up with font-weight: 400, while expected font-weight should be 600. Problem would not appear, if .name, .name-small would appear before .name selector.

### Version

5.1.12

### Preset

default

### Environment

```shell
Ubuntu 18.04, Bash
```

### Package details

```shell
postcss@8.4.5
```

### Additional context

Can be reproed in cssnano playground.
