### ISSUE TITLE
[Bug]: postcss-reduce-initial transforms `mask-repeat: no-repeat` to `mask-repeat: initial`

### ISSUE THREAD

**Issue by dakur** [cssnano/cssnano#1452]
### Describe the bug

Running cssnano with `postcss-reduce-initial` transforms

```css
.el {
  mask-repeat: no-repeat;
}
```

to 

```css
.el {
  mask-repeat: initial;
}
```

But as you can try in [this codepen](https://codepen.io/dakur/pen/jOKyLop), initial behavior of `mask-repeat` is not actually `no-repeat`, but `repeat`. (Chrome, FF, Safari)

### Expected behaviour

Output

```css
.el {
  mask-repeat: no-repeat;
}
```

### Steps to reproduce

Run cssnano with the aforementioned plugin and code snippet.

### Version

5.1.14

### Preset

default

### Environment

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (8) x64 Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
  Memory: 3.24 GB / 15.99 GB
```

### Package details

```shell
├─ cssnano@5.1.14
└─ postcss@8.4.18
```

### Additional context

Workaround: ignore such property

E.g. in `cssnano.config.js`:

```js
const defaultPreset = require('cssnano-preset-default');

module.exports = defaultPreset({
	reduceInitial: {
		exclude: ['mask-repeat'],
	},
});
```
