### ISSUE TITLE
[Bug]: mergeLonghand should not merge an invalid property with a valid one

### ISSUE THREAD

**Issue by jathak** [cssnano/cssnano#1454]
### Describe the bug

`mergeLonghand` currently merges properties even when one of them is invalid.

For example, code like:
```css
a {
  margin-top: 10px;
  margin-left: 20px;
  margin-right: 30px;
  margin-bottom: invalid;
}
```
is minified to:
```
a{margin:10px 30px invalid 20px}
```

This changes the behavior of the code, as in the longhand form, only the invalid bottom margin is ignored by the browser. When the margins are combined, the combined property is now invalid, so the browser ignores all the margins.

### Expected behaviour

Valid and invalid longhand properties should not be merged.

### Steps to reproduce

Copy the example above into https://cssnano.co/playground/

### Version

5.1.14

### Preset

default

### Environment

```shell
https://cssnano.co/playground/
```

### Package details

```shell
Whatever the playground is using
```
