### ISSUE TITLE
[Feature Request]: postcss-normalize-whitespace should fold whitespace within var()

### ISSUE THREAD

**Issue by nex3** [cssnano/cssnano#1457]
### What should be improved?

Currently, postcss-normalize-whitespace doesn't compress whitespace at all within `var()` function calls. For example, `var(  --foo  )` is emitted as-is rather than as `var(--foo)` or `var( --foo )`.

### Describe the solution you would like

Within a normal property, whitespace before the first comma in `var()` should be removed completely and whitespace after the first comma should be folded down to a single space or removed depending on the context of the `var()`. For example:

```css
/* input */
a {
  b: var(
    --foo
  );
}
```

```css
/* output */
a{b:var(--foo)}
```

Within a custom property, since it may be interpreted by JavaScript rather than CSS (see https://github.com/cssnano/cssnano/issues/1456), whitespace should be folded down to the smallest form that produces an equivalent serialization: a single space. For example:

```css
/* input */
a {
  --b: var(
    --foo
  );
}
```

```css
/* output */
a{--b: var( --foo )}
```

### Additional context

N/A

### Are you willing to work on this?

- [ ] Yes, I would like to help
