### ISSUE TITLE
[Bug]: `reduceIdents: false` not working

### ISSUE THREAD

**Issue by argyleink** [cssnano/cssnano#1460]
### Describe the bug

I have some keyframes being transformed into a broken state:
```css
@keyframes author-scroll-effect {
  exit -5%, 0% {
    transform: scale(1);
  }
  exit 50%, exit 100% {
    transform: scale(0.8) translateY(10vh);
  }
}
```

becoming

```css
@keyframes author-scroll-effect {
  exit -5%, 0% {
    transform: scale(1);
  }
  exit 50%, exit to {
    transform: scale(0.8) translateY(10vh);
  }
}
```

I'm pretty savvy with build tools and nothing I did could remove that transform, makes me think it's got a bug? or let me know how I'm holding it wrong. it's strange too because i'm not passing a preset (well, i wasnt at first but i've tried passing presets) and the only way i can get rid of the transform is by using the "lite" preset. This is odd because the default preset shouldnt even include this transform..?

![Screen Shot 2022-12-15 at 3 29 31 PM](https://user-images.githubusercontent.com/1134620/207988462-892a4083-4cc7-45c9-b1ec-8661f53a921f.png)

I was hoping this simple config would do it, but i've tried all the presets and stuff.

```js
cssnano({
  reduceIdents: false
})

cssnano({
  reduceIdents: { keyframes: false }
})
```

### Expected behaviour

I expected being able to disable the transform but found I could only do it by heavily downgrading the optimizations to the lite preset. 

### Steps to reproduce

1. use latest node
2. use latest cssnano and postcss
3. try and remove the `reduceIdents` transform

### Version

latest

### Preset

default

### Environment

```shell
System:
    OS: macOS 12.6.1
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
    Memory: 476.42 MB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
```

### Package details

```shell
cssnano and postcss
```
