### ISSUE TITLE
[Bug]: `mergeLonghand` rule from default preset removes fallback styles

### ISSUE THREAD

**Issue by grzegorzpokorski** [cssnano/cssnano#1461]
### Describe the bug

https://cssnano.co/playground/#eyJpbnB1dCI6Ii8qIHdyaXRlIHlvdXIgY3NzIGJlbG93ICovXG4uZm9vMSB7XG4gIGNvbG9yOiByZWQ7IC8qIGZhbGxiYWNrICovXG4gIGNvbG9yOiBibHVlO1xufVxuLmZvbzIge1xuXHRib3JkZXItd2lkdGg6IDEwcHg7XG5cdGJvcmRlci1zdHlsZTogc29saWQ7XG4gIGJvcmRlci1jb2xvcjogcmdiYSgyNTUsMCwwKTsgLyogZmFsbGJhY2sgKi9cbiAgYm9yZGVyLWNvbG9yOiBva2xjaCg2Mi44JSwgNjQuNSUsIDI5LjIzNCUpO1xufSIsImNvbmZpZyI6ImNzc25hbm8tcHJlc2V0LWRlZmF1bHQifQ==

### Expected behaviour

Expect to preserve fallback styles, instead this:

input:
```css
.foo1 {
  color: red; /* fallback */
  color: blue;
}
.foo2 {
  border-width: 10px;
  border-style: solid;
  border-color: rgba(255,0,0); /* fallback */
  border-color: oklch(62.8%, 64.5%, 29.234%);
}
```
output:
```css
.foo1{color:red;color:blue}.foo2{border:10px solid oklch(62.8%,64.5%,29.234%)}
```

should be:

input:
```css
.foo1 {
  color: red; /* fallback */
  color: blue;
}
.foo2 {
  border-width: 10px;
  border-style: solid;
  border-color: rgba(255,0,0); /* fallback */
  border-color: oklch(62.8%, 64.5%, 29.234%);
}
```
output:
```css
.foo1{color:red;color:blue}.foo2{border:10px solid rgba(255,0,0);border:10px solid oklch(62.8%,64.5%,29.234%);}
```

### Steps to reproduce

1. install postcss and cssnano then configure them together
2. set cssnano-preset-default in postcss config file to be use by cssnano
3. try to minify css code from 'expected behaviour' section of this issue

### Version

^5.0.3

### Preset

default

### Environment

```shell
OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 10.00 GB / 12.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
```

### Package details

```shell
"cssnano": "^5.0.3"
"postcss": "^8.4.4"
```

**Comment by grzegorzpokorski** [comment]
I got around this problem by simply use CSS variables and `@supports` CSS at-rule - example below:
```css
:root{
 --custom-color: rgb(245, 255, 255);
}

@supports (color: color(display-p3 0 0 0)) {
 :root {
  --custom-color: color(display-p3 0.96859 1.00000 1.00000);
 }
}

.foo2 {
  border-color: var(--custom-color);
}
```

 By doing that I no longer need falback styles like this:
```css
.foo2 {
  border-color: rgba(255,0,0); /* fallback */
  border-color: oklch(62.8%, 64.5%, 29.234%);
}
```
so, sssnano has nothing to remove.
