### ISSUE TITLE
[Bug]: cssnano misinterprets unquoted font name as color

### ISSUE THREAD

**Issue by Invizory** [cssnano/cssnano#1463]
### Bug Description

Consider the following CSS (all irrelevant properties are omitted):

```css
@font-face {
  src: local(Noto Sans Black);
}
```

Here, `Black` is misinterpreted by `cssnano` as the name of the color, resulting in:

```css
@font-face{src:local(Noto Sans #000)}
```

However, if one quotes a font face name, the problem disappears:

```css
@font-face {
  src: local("Noto Sans Black");
}
```

The above example minifies to:

```css
@font-face{src:local("Noto Sans Black")}
```

However, according to [CSS Fonts Module Level 3](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-face-name-value) W3C recommendation, quotes are optional:

> The syntax for a [`<font-face-name>`](https://www.w3.org/TR/2018/REC-css-fonts-3-20180920/#font-face-name-value) is a unique font face name enclosed by `"local("` and `")"`. The name can **optionally** be enclosed in quotes. If unquoted, the unquoted font family name processing conventions apply; the name must be a sequence of identifiers separated by [whitespace](https://www.w3.org/TR/css3-syntax/#whitespace) which is converted to a string by joining the identifiers together separated by a single space.

It looks like the bug originates from `postcss-colormin`, which tries to [minify color names within too many contexts](https://github.com/cssnano/cssnano/blob/a32df1ab19bac91220a96e2af2cc4130dbd2c7ac/packages/postcss-colormin/src/index.js#L126) without limiting oneself to the contexts where only colors can appear.

Maybe it's a good idea to add the following test to `cssnano/packages/postcss-colormin/test/index.js` and make it pass:

```js
test(
  'should not attempt to convert unquoted font names',
  passthroughCSS('@font-face{src:local(Noto Sans Black)}')
);
```

### Expected behaviour

```css
@font-face{src:local(Black Font Name)}
```

### Steps to reproduce

Minify the stylesheet provided above with [cssnano playground](https://cssnano.co/playground/) or latest (`5.1.14`) version of `cssnano`.

### Version

5.1.14

### Preset

default

### Environment

```shell
System:
  OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Memory: 2.37 GB / 15.40 GB
  Container: Yes
  Shell: 5.8.1 - /usr/bin/zsh
```
