### ISSUE TITLE
[Bug]: Borders rules with logical properties are not ordered correctly.

### ISSUE THREAD

**Issue by Westbrook** [cssnano/cssnano#1502]
### Describe the bug

When using `border-end-start-radius` with `border-radius` the declarations are ordered incorrectly.

```css
.selector {
  border-radius: 5px;
  border-end-start-radius: 0;
  border-end-end-radius: 0;
}
```

Becomes:

```css
.selector{
  border-end-end-radius:0;
  border-end-start-radius:0;
  border-radius:5px;
}
```

The shorthand overrides the longhand and the outcome is incorrect border radii.

### Expected behaviour

The declaration order should follow something similar to what is done with other border longhand rules in relationship to the shorthand and always have the shorthand at the beginning. This currently happens with illogical properties (`bottom-right` and `bottom-left`):

```css
.selector {
  border-radius: 5px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
}
```

Becomes 

```css
.selector{
  border-radius:5px;
  border-bottom-left-radius:0;
  border-bottom-right-radius:0;
}
```

### Steps to reproduce

1. Visit https://cssnano.co/playground/
2. Apply the following sample code:
    ```css
    .selector {
      border-radius: 5px;
      border-end-start-radius: 0;
      border-end-end-radius: 0;
    }
    ```
3. See the output.

### Version

All

### Preset

default

### Environment

```shell
Playground site, et al.
```

### Package details

```shell
Playground site, et al.

`cssnano@>5.0.15`
```
