### ISSUE TITLE
[Bug]: Incorrect layer order after minification

### ISSUE THREAD

**Issue by devongovett** [cssnano/cssnano#1544]
### Describe the bug

I was investigating https://github.com/parcel-bundler/lightningcss/issues/571 in Lightning CSS and noticed that cssnano also has incorrect behavior. 

```css
@layer a {}
@layer b {}

@layer b {
  foo {
    color: red;
  }
}

@layer a {
  bar {
    color: green;
  }
}
```

currently minifies to:

 ```css
@layer b{foo{color:red}}@layer a{bar{color:green}}
```

But the layers are now in the wrong order.

### Expected behaviour

Should either preserve empty layers, reorder them, or add `@layer a,b;` at the start of the file to preserve the order.

### Steps to reproduce

see above

### Version

latest

### Preset

default

### Environment

```shell
tested in the playground
```

### Package details

```shell
https://cssnano.co/playground/
```
