### ISSUE TITLE
[Bug]: Empty blocks within @layer rule are not deleted and sometimes @layers blocks are not merged

### ISSUE THREAD

**Issue by Yoskutik** [cssnano/cssnano#1594]
### Describe the bug

If my CSS code contains several instances of using `@layer` rule with the same layer name, after the minification CSS nano will keep each usage of it.

This code

```css
@layer components {
  .O82 { display: flex; }
}
@layer components {
  .tK5 { border: 0; }
}
@layer components {
  .tK1 { font-size: inherit; }
}
```

Is compiled into this (I added whitespaces)

```css
@layer components {
  .O82 { display: flex }

  .tK5 { border: 0 }

  .tK1 { font-size: inherit }
}

@layer components {}

@layer components {}
```

### Expected behaviour

The following `@layer components {}` blocks do not affect the styles, therefore they can be removed

### Steps to reproduce

The steps are described above

### Version

6.1.2

### Preset

default

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 113.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
```

### Package details

```shell
├─┬ css-loader@6.10.0 -> ./node_modules/.pnpm/css-loader@6.10.0_webpack@5.91.0/node_modules/css-loader
│ ├─┬ icss-utils@5.1.0 -> ./node_modules/.pnpm/icss-utils@5.1.0_postcss@8.4.38/node_modules/icss-utils
│ │ └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
│ ├─┬ postcss-modules-extract-imports@3.0.0 -> ./node_modules/.pnpm/postcss-modules-extract-imports@3.0.0_postcss@8.4.38/node_modules/postcss-modules-extract-imports
│ │ └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
│ ├─┬ postcss-modules-local-by-default@4.0.4 -> ./node_modules/.pnpm/postcss-modules-local-by-default@4.0.4_postcss@8.4.38/node_modules/postcss-modules-local-by-default
│ │ └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
│ ├─┬ postcss-modules-scope@3.1.1 -> ./node_modules/.pnpm/postcss-modules-scope@3.1.1_postcss@8.4.38/node_modules/postcss-modules-scope
│ │ └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
│ ├─┬ postcss-modules-values@4.0.0 -> ./node_modules/.pnpm/postcss-modules-values@4.0.0_postcss@8.4.38/node_modules/postcss-modules-values
│ │ └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
│ └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
└─┬ css-minimizer-webpack-plugin@6.0.0 -> ./node_modules/.pnpm/css-minimizer-webpack-plugin@6.0.0_webpack@5.91.0/node_modules/css-minimizer-webpack-plugin
  ├─┬ cssnano@6.1.2 -> ./node_modules/.pnpm/cssnano@6.1.2_postcss@8.4.38/node_modules/cssnano
  │ └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
  └── postcss@8.4.38 -> ./node_modules/.pnpm/postcss@8.4.38/node_modules/postcss
```

**Comment by ludofischer** [comment]
This happens because deleting an empty layer might change the layer priority (see closed issue https://github.com/cssnano/cssnano/issues/1544). To prevent keeping useless empty layers, cssnano should remember all the layer names it has seen before, but currently it does not do it.

**Comment by ludofischer** [comment]
> When why do you merge the styled into a single layer declaration? If you have to keep the layers, isn't better not to merge them?

As far as I remember, the code that merges is the same for all at-rules, and predates even existence of `@layer` declarations. When layers became more widespread, a fix was applied to preserve empty at-rules only for the `@layer`  case.

**Comment by Yoskutik** [comment]
Hello. Right now I realized, merging is also not working as good as it could if there's nesting of at-rules or styles. Here's a short example

```css
@layer layer {
  @scope (.class1) { 
    .class1-child {
      color: red;
    }
  }

  @scope (.class2) { 
    .class2-child {
      color: red;
    }
  }
}

@layer layer {
  @scope (.class1) { 
    .class1-child {
      font-size: 1px;
    }
  }

  @scope (.class2) { 
    .class2-child {
      font-size: 1px;
    }
  }
}
```

Is compiled into

```css
@layer layer{@scope (.class1){.class1-child{color:red}}@scope (.class2){.class2-child{color:red}}}@layer layer{@scope (.class1){.class1-child{font-size:1px}}@scope (.class2){.class2-child{font-size:1px}}}
 ```
 
 While it could be 37% shorter
 
 ```css
 @layer layer{@scope (.class1){.class1-child{color:red;font-size:1px}}@scope (.class2){.class2-child{color:red;font-size:1px}}}}
 ```
 
 Also, thank you for letting me know that not removing empty layers can change the layer priority. But if layers are configured properly, the change is not possible. Can you please add a configuration to the advanced preset, so a developers could decide whether they want to remove empty layers or not?
