### ISSUE TITLE
[Bug]: `@layer` rules without a block overwrite previously declared rules

### ISSUE THREAD

**Issue by devongovett** [cssnano/cssnano#1655]
### Describe the bug

This input CSS:

```css
@layer b {
  body {
    color: green;
  }
}

@layer b;
```

results in the first `@layer` rule being deleted.

### Expected behaviour

It should be equivalent to the output from this:

```css
@layer b {
  body {
    color: green;
  }
}

@layer b {}
```

`@layer` rules without a block should be treated the same as if they had an empty block.

See this codepen for how it behaves in the browser: https://codepen.io/devongovett/pen/YzoxjPM

### Steps to reproduce

see above

### Version

latest

### Preset

default

### Environment

```shell
tested in the playground
```

### Package details

```shell
https://cssnano.github.io/cssnano/playground/
```

### Additional context

Related upstream bug in Next.js https://github.com/vercel/next.js/issues/68476
