### ISSUE TITLE
[Bug]: `CanvasText` is not the same as `initial`, should not be replaced

### ISSUE THREAD

**Issue by krokodok** [cssnano/cssnano#1660]
### What should be improved?

I am trying to make a website more accessible for Windows High Contrast Mode / forced-colors media query. I want to style my elements with the system colors from CSS Color Module Level 4: https://www.w3.org/TR/css-color-4/#css-system-colors

But currently my keywords get transformed to `initial`, which is not the same. (But not all of them?)

```css
// Input
.my-element {
    color: CanvasText;
    background: Canvas;
}

// Output
.my-element {
    color: initial;
    background: Canvas;
}
```

Currently I am relying on a workaround using a custom property:
```css
.my-element {
    --CanvasText: CanvasText;
    color: var( --CanvasText );
    background: Canvas;
}
```

### Describe the solution you would like

It would be great for the list of CSS Color Module Level 4 System Color keywords to be always respected and not transformed to `initial`.

### Additional context

I am not too familiar with cssnano. There might be a way to already do this, or an easier workaround. But I could not find any.

### Are you willing to work on this?

- [X] Yes, I would like to help

**Comment by krokodok** [comment]
It seems that this is a problem in `postcss-reduce-initial`. I will open a new issue there.

**Comment by ludofischer** [comment]
We can keep this open since `postcss-reduce-initial` is in this same repository.

**Comment by krokodok** [comment]
Never mind! I used an outdated version of the package…

**Comment by krokodok** [comment]
Sorry! I was confused with my setup! Now I found the issue again!

It is here in this line:
https://github.com/cssnano/cssnano/blob/104c3035a99af1a23fd53b315d105fdd8df030e3/packages/postcss-reduce-initial/src/data/toInitial.json#L18

`canvastext` is _not_ the same as `initial`. An easy example is, if I want to change the styling of an element of which the initial color is something different than `canvastext`, for example a `mark` element:

```css
// Remove mark highlight in forced-colors mode
@media (forced-colors: active) {
    mark {
        background: Canvas;
        color: CanvasText;
    }
}
```

If `Canvas` is black and the initial color for `mark` is black my text won't be readable.
