### ISSUE TITLE
[Feature Request]: Optionally use :is()

### ISSUE THREAD

**Issue by stevenvachon** [cssnano/cssnano#1703]
### What should be improved?

https://developer.mozilla.org/en-US/docs/Web/CSS/:is#simplifying_list_selectors

### Describe the solution you would like

Use `:is()`,

### Additional context

--

### Are you willing to work on this?

- [ ] Yes, I would like to help

**Comment by ludofischer** [comment]
Thank you for the suggestion. It looks interesting. In these cases I tend to worry about the potential to introduce bugs compared to the size reduction gains. Have you got examples where this brings benefit, perhaps in minifying generated code? I could imagine developers would tend to write `:is` in the first place since it is shorter and more readable than the alternative.

**Comment by stevenvachon** [comment]
There is at least a situation like generated code from SCSS where it will contain unoptimized code without the use of `:is()`, such as:

```scss
%placeholder {
  color: red
}

ol li a {
  @extend %placeholder;
}

ul li a {
  @extend %placeholder;
}
```
