### ISSUE TITLE
Discussion: transformation to lowercase?

### ISSUE THREAD

**Issue by MattDiMu** [cssnano/cssnano#197]
Accoring to the specs, "everything under control of CSS" is case-insensitive. Exceptions (not under control) are for example classNames, IDs, url-fragments, etc.

From a compression point of view (e.g. file is transfered via gzip), it's preferable to have similar Strings. Therefore the transfered size of a CSS could be reduced by simply transforming all case-insensitive parts to lowercase.

Do you think some sort of postcss-transform-to-lowercase plugin could be useful? I might be willing to work on something like that, if it has a realistic chance of making it into cssnano :)

Regards
MattDiMu

**Comment by ben-eb** [comment]
Personally I've not seen this come up before, but it does make sense to perform this transform if it yields some gzip benefit in a real-world project. We already do *some* lower casing, for instance in colours. https://github.com/ben-eb/colormin/blob/master/src/index.js#L39-L46

I've also made a poll to see if there are people who would use other notation;

https://twitter.com/ben_eb/status/733687467644223488

If you'd like to do the work then I'm all for it. 😄

**Comment by Justineo** [comment]
AFAIK, values with type `<custom-ident>` are case sensitive in CSS. For `<string>` values and selectors, case sensitivity depends on things beyond CSS scope such as document types (HTML/XML/...).

```css
@import "MayBeCaseSensitive.css";

[data-text="May Be Case sensitive."]::after {
  content: "Probably Case sensitive.";
  background-image: url("May/Be/Case/Sensitive.png");
}

@keyframes CaseSensitive {
  /* blah blah */
}
```
