### ISSUE TITLE
Feature: Reduce grid definitions

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#261]
Input:

``` css
#page {
  display: grid;
  width: 100%;
  height: 250px;
  grid-template-areas: "head head"
                       "nav  main"
                       "nav  foot";
  grid-template-rows: 50px 1fr 30px;
  grid-template-columns: 150px 1fr;
}

#page > header {
  grid-area: head;
  background-color: #8ca0ff;
}
```

Output:

``` css
#page {
  display: grid;
  width: 100%;
  height: 250px;
  grid-template-areas: "a a"
                       "b c"
                       "b d";
  grid-template-rows: 50px 1fr 30px;
  grid-template-columns: 150px 1fr;
}

#page > header {
  grid-area: a;
  background-color: #8ca0ff;
}
```

**Comment by sylvainpolletvillard** [comment]
Further optimization:

```
#page {
  display: grid;
  width: 100%;
  height: 250px;
  grid-template: "a a" 50px "b c" 1fr "b d" 30px / 150px 1fr;
}
```

I think the renaming part and the `grid-template` syntax part should be two distinct optimizations, so that we can optimize the properties while keeping the original zone identifiers.

I need this for postcss-grid-kiss so I may try to work on it :smile:

**Comment by ben-eb** [comment]
@sylvainpolletvillard That would be really great! I think for now that this can be a separate module, would you be amenable to merging it into this repository after it's converted to a monorepo?

I thought for the actual identifier renaming we can re-use https://github.com/ben-eb/postcss-reduce-idents/blob/master/src/lib/encode.js. 😄 

Oh and also, grid syntax allows the usage of `.` for empty grid areas, but you can use as many of these consecutively as you wish:

```css
body {
  grid-template-areas: "advert .... nav"
                                      "advert .... nav";
}
```

We can reduce these to a single `.` too.
