### ISSUE TITLE
Feature: Extract property values into variables when shorter.

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#264]
Input:

``` css
h1 {
  margin: 1.34781748921321rem;
}

h2 {
  left: 1.34781748921321rem;
}
```

Output:

``` css
:root {
  --a: 1.34781748921321rem;
}

h1 {
  margin: var(--a);
}

h2 {
  left: var(--a);
}
```

**Comment by Siilwyn** [comment]
The latest versions of the browser Edge still have known issues with CSS variables not to mention the lacking support for it in older browsers. This would be a very dangerous one to include as developers might not notice this breaking support for older browsers. Maybe disable it by default, even in the advanced preset, making it explicit opt-in?

That said your example exactly increases the gzipped size from 75 to 94 bytes. Even when using the same value four times it still increases the gzipped size:
```css
/* 90 bytes */
h1 {
  margin: 1.34781748921321rem;
}

h2 {
  left: 1.34781748921321rem;
  top: 1.34781748921321rem;
  right: 1.34781748921321rem;
}
```

```css
/* 109 bytes */
:root {
  --a: 1.34781748921321rem;
}

h1 {
  margin: var(--a);
}

h2 {
  left: var(--a);
  top: var(--a);
  right: var(--a);
}
```
