### ISSUE TITLE
Feature: Inline custom properties when shorter (unsafe)

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#265]
Input:

``` css
:root {
  --foo: red;
}

h1 {
  color: var(--foo);
}
```

Output:

``` css
h1 {
  color: red;
}
```
