### ISSUE TITLE
Turn off `mergeRules` for specific rules

### ISSUE THREAD

**Issue by iandevlin** [cssnano/cssnano#411]
Is it possible to switch `mergeRules` off for a specific item? At the moment I have a problem where this rule is merging `@supports` which then causes things to break, as the rule within `@supports` is actually supposed to override something but the ordering that it output is incorrect.

I know  that I can turn off `mergeRules` for everything, but I was wondering if I could do it for `@supports` rules only.

**Comment by benmcginnis** [comment]
To add some code to explain this issue, I'm seeing rules from within `@supports` get merged when a media query is underneath the `@supports` rule:

``` css
/* media in supports: input */
@media (min-width: 48rem) {
  .wrapper {
    -ms-grid-row: 4;
        grid-row-start: 4;
    -ms-grid-row-span: 1;
        grid-row-end: span 1;
  }
}

@supports (object-fit: cover) {
  @media (min-width: 48rem) {
      .wrapper {
        position: relative;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: column;
            flex-direction: column;
        -ms-flex-align: stretch;
            align-items: stretch;
        -ms-flex-pack: center;
            justify-content: center;
      }

      .cover-image {
        object-fit: cover;
        width: 100%;
        height: 100%;
      }
  }
}

/* bad output */

@media (min-width:48rem) {
  .wrapper {
    -ms-grid-row: 4;
    grid-row-start: 4;
    -ms-grid-row-span: 1;
    grid-row-end: span 1;
    position: relative;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-direction: column;
    flex-direction: column;
    -ms-flex-align: stretch;
    align-items: stretch;
    -ms-flex-pack: center;
    justify-content: center
  }
}

@supports (object-fit:cover) {
  @media (min-width: 48rem) {
    .cover-image {
      object-fit:cover;
      width: 100%;
      height: 100%
    }
  }
}

/* supports in media: input */
@media (min-width: 48rem) {
  .wrapper {
    -ms-grid-row: 4;
        grid-row-start: 4;
    -ms-grid-row-span: 1;
        grid-row-end: span 1;
  }
}

@media (min-width: 48rem) {
  @supports (object-fit: cover) {
      .wrapper {
        position: relative;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: column;
            flex-direction: column;
        -ms-flex-align: stretch;
            align-items: stretch;
        -ms-flex-pack: center;
            justify-content: center;
      }

      .cover-image {
        object-fit: cover;
        width: 100%;
        height: 100%;
      }
  }
}

/* good output: */
@media (min-width:48rem) {
  .wrapper {
    -ms-grid-row: 4;
    grid-row-start: 4;
    -ms-grid-row-span: 1;
    grid-row-end: span 1
  }
}

@media (min-width:48rem) {
  @supports (object-fit: cover) {
    .wrapper {
      position:relative;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-direction: column;
      flex-direction: column;
      -ms-flex-align: stretch;
      align-items: stretch;
      -ms-flex-pack: center;
      justify-content: center
    }
    .cover-image {
      object-fit: cover;
      width: 100%;
      height: 100%
    }
  }
}

```

**Comment by evilebottnawi** [comment]
@andyjansson Looks we should ignore merge rule inside `@supports`

**Comment by evilebottnawi** [comment]
@benmcginnis can we reduce bug example?

**Comment by evilebottnawi** [comment]
Example:

Input:
```css
@media (min-width: 48rem) {
  .wrapper {
    display: block;
  }
}

@supports (display: flex) {
  @media (min-width: 48rem) {
      .wrapper {
        display: flex
      }
  }
}
```

Output:
```css
@media (min-width:48rem){.wrapper{display:block;display:flex}}
```

Expected don't merge same at-rules in `@supports`
