### ISSUE TITLE
parse font-family name with slash is something wrong?

### ISSUE THREAD

**Issue by xinglie** [cssnano/cssnano#439]
Hi 
  I have a css font-family rule write use unicode like this

```css
textarea {
  font-family: 'helvetica neue','wenquanyi micro hei','\5FAE\8F6F\96C5\9ED1', '\5B8B\4F53', sans-serif;
}
```
use cssnano compress it . the result  is
```css
textarea{font-family:helvetica neue,wenquanyi micro hei,\\5FAE\8F6F\96C5\9ED1,\\5B8B\4F53,sans-serif}
```

is this wrong or i miss something?
