### ISSUE TITLE
mergeLonghand is not always a safe transformation

### ISSUE THREAD

**Issue by philipwalton** [cssnano/cssnano#448]
The [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) plugin sets fallbacks for properties that use native CSS custom properties. Unfortunately, I noticed cssnano was stripping these fallbacks out, and I traced it back to the mergeLonghand plugin.

Here's an example of what `postcss-custom-properties` does that gets stripped by mergeLonghand:

```css
:root {
  --gutter: 1em;
}

.component {
  padding: var(--gutter);
}

/* becomes */

:root {
  --gutter: 1em;
}

.component {
  padding: 1em;  
  padding: var(--gutter);
}
```

But since cssnano sees two `padding` declarations, it tries to combine them to a single, longhand version. However, when doing that the fallback is lost.
