### ISSUE TITLE
[Bug] named grid-template-columns are not renamed while grid-area does

### ISSUE THREAD

**Issue by gijsroge** [cssnano/cssnano#529]
version: 3.10.0
preset: default

input: 
```scss
.test{
  grid-template-columns: [image] 100px [info] auto;
}

.test a{
  grid-area: image;
}
```

cssnano output:
```scss
.test {
  grid-template-columns: [image] 100px [info] auto
}

.test a {
  grid-area: a
}
```
