### ISSUE TITLE
Bizzare output on "border" values

### ISSUE THREAD

**Issue by mission712** [cssnano/cssnano#540]
Processing the following:
```css
#hovering-postform:checked ~ .post-form input[type=text],    
#hovering-postform:checked ~ .post-form input[type=password],
#hovering-postform:checked ~ .post-form textarea {           
  display: block;                                            
                                                             
  border: none;                                              
  margin: 0;                                                 
  border-bottom: var(--hovering-border);                     
  background-color: var(--hovering-bg);                      
  color: var(--hovering-fg);                                 
}                                                            
```
gives me the following.
```css
#hovering-postform:checked~.post-form input[type=password],#hovering-postform:checked~.post-form input[type=text],#hovering-postform:checked~.post-form textarea{background-col
or:#fff;background-color:var(--hovering-bg);border:none currentColor;border-bottom-width:var(--hovering-border);border-width:none none 1px;color:#000;color:var(--hovering-fg);disp
lay:block;margin:0}
```
Note things like `border:none currentColor;` and `border-bottom-width:var(--hovering-border);border-width:none none 1px;`.
This causes a weird border with the text color, while the unminified CSS doesn't have this issue.

PostCSS configuration:
```js
module.exports = {                 
  plugins: [                       
    require('postcss-preset-env')({
      stage: 3,                    
      browsers: 'defaults',        
    }),                            
    require('cssnano')({           
      preset: 'default',           
    }),                            
  ],                               
};                                 
```

**Comment by evilebottnawi** [comment]
@mission712 PR welcome, will be great if you reduce example to small, it is allow other people have actual and expected output and easy and fast fix it

**Comment by evilebottnawi** [comment]
@mission712 which version of `cssnano` you use?

**Comment by JaZo** [comment]
I have this same issue.

Input:
```css
.header {
  border-bottom: var(--header__border-bottom, none);
}
```

Output:
```css
.header{border-bottom-color:currentColor;border-bottom-style:none;border-bottom-width:var(--header__border-bottom,none)}
```

Version: 4.0.1
Preset: default

**Comment by evilebottnawi** [comment]
@JaZo thanks, looks bug, feel free to send a PR :+1:

**Comment by equinusocio** [comment]
Similar issue here:

**input**
```css
input {
	--textfieldBorder: var(--ne-textfield-border, 1px solid hsl(0, 0%, 89%));
	border: var(--textfieldBorder);
}
```

**output**
```css
input {
    border: var(--textfieldBorder);
    border-color: currentColor;
}
```

This is issue is blocking for me because i can't remove/override the `border-color: currentColor` property that cause a weird style corruption that block my releases :(
