### ISSUE TITLE
Unexpected border-color property when using custom properties.

### ISSUE THREAD

**Issue by equinusocio** [cssnano/cssnano#550]
Hi, it seems that `4.0.2` does not fix this issue. When using a custom property as value of any `border*` property **cssnano** adds a `border-*-color: currentColor` property that cause ugly style and can't be overwritten. The optimisation that cause this issue is `postcss-merge-longhand`. Right now the only way to avoid this issue is to disable this optimisation.

This issue is blocking for me because i can't remove/override the `border-color: currentColor` property that cause a weird style corruption that blocks my release :(

Version: 4.0.2
Preset: default | advanced

**input**
```css
:root {
	--textfieldBorder: var(--ne-textfield-border, 1px solid hsl(0, 0%, 89%));
}

input {
	border: var(--textfieldBorder);
}
```

**output**
```css
input {
    border: var(--textfieldBorder);
    border-color: currentColor;
}
```

May be related to #540

**Comment by andyjansson** [comment]
I can't reproduce your results.

```js
const postcss = require('postcss');
const cssnano = require('cssnano');
const fs = require('fs');


fs.readFile('input.css', (err, css) => {
    postcss([ cssnano({ preset: 'default' }) ])
        .process(css, { from: 'input.css', to: 'output.css' })
        .then(result => {
            fs.writeFile('output.css', result.css);
        });
});
```

`input.css`: 
```css
:root {
	--textfieldBorder: var(--ne-textfield-border, 1px solid hsl(0, 0%, 89%));
}

input {
	border: var(--textfieldBorder);
}
```

`output.css`:

```css
:root{--textfieldBorder:var(--ne-textfield-border,1px solid #e3e3e3)}input{border:var(--textfieldBorder)}
```

Check your lockfile?
