### ISSUE TITLE
Incorrect merging of border declarations

### ISSUE THREAD

**Issue by andyjansson** [cssnano/cssnano#551]
As originally reported [here](https://github.com/ben-eb/postcss-merge-longhand/issues/26):

# Case 1

## Input

```css
.merge-longhand {
  border: 1px solid black;
  border-top-width: 2px;
  border-right-width: 2px;
  border-bottom-width: 2px;
}
```
## Output

```css
.merge-longhand {
  border: 2px solid black;
  border-left: solid black;
  border-width: 1px;
}
```
## Expected

```css
.merge-longhand {
  border: solid black;
  border-width: 2px 2px 2px 1px;
}
```

# Case 2

## Input

```css
.merge-longhand {
  border: none;
  border-top: 6px solid #000;
  border-bottom: 1px solid #fff;
}
```
## Output

```css
.merge-longhand {
  border: 6px solid #000;
  border-left: none;
  border-right: none;
}
```
## Expected

```css
.merge-longhand {
  border: none;
  border-top: 6px solid #000;
  border-bottom: 1px solid #fff;
}
```

Thanks to @apriljunge and @implico for reporting these issues.
