### ISSUE TITLE
mergeLonghand removes things it shouldn't remove

### ISSUE THREAD

**Issue by hudochenkov** [cssnano/cssnano#554]
`mergeLonghand` removes CSS in `cssnano@4.0.2`.

Input:

```css
.b {
    border-top-color: rgba(85, 85, 85, 0.95);
    border-bottom: none;
}
```

Output:

```css
.b {
  border-bottom: none;
}
```
