### ISSUE TITLE
CSS rule gets removed entirely

### ISSUE THREAD

**Issue by bytasv** [cssnano/cssnano#556]
Hello,

I'm running dev and prod builds and using cssnano to minify css, here are screens of dev and prod versions output:

DEV:
```css
.ui.secondary.vertical.pointing.menu {
    border-right: none;
}

.ui.secondary.vertical.pointing.menu {
    border-bottom-width: 0px; /* <--- this rule is dropped */
    border-right-width: 0.125rem;
    border-right-style: solid;
    border-right-color: rgba(34, 36, 38, 0.15);
}

.ui.secondary.pointing.menu {
    margin-left: 0em;
    margin-right: 0em;
    border-bottom: 0.125rem solid rgba(34, 36, 38, 0.15);
}
```

PROD:
```css
.ui.secondary.vertical.pointing.menu {
    border-right: none;
}
.ui.secondary.vertical.pointing.menu {
    border-right: .125rem solid rgba(34,36,38,.15);
}
.ui.secondary.pointing.menu {
    border-bottom: .125rem solid rgba(34,36,38,.15);
    margin-left: 0;
    margin-right: 0;
}
```

You can see that for some reason CSS nano decides to remove `border-bottom` rule (obvious visual flaw appears)

I'm pretty sure this is an issue as it shouldn't drop rules like that. I've tried using both presets `default` and `advanced` none behaves differently.

I couldn't also find which specific rule triggers this behaviour, I tried disabling all rules by one, but nothing seemed to make difference (maybe I used bad configuration)

**Comment by evilebottnawi** [comment]
@bytasv please try `cssnano@4.0.3`, we should fixed this in new version

**Comment by bytasv** [comment]
@evilebottnawi 

```
cssnano@4.0.3:
  version "4.0.3"
  resolved "https://registry.yarnpkg.com/cssnano/-/cssnano-4.0.3.tgz#b694d626906bf1844f573465ecc166b2240b8699"
  dependencies:
    cosmiconfig "^5.0.0"
    cssnano-preset-default "^4.0.0"
    is-resolvable "^1.0.0"
    postcss "^6.0.0"
```

I've checked it :(

**Comment by bytasv** [comment]
@evilebottnawi I'm trying to disabled offending rule like so:
```
  new OptimizeCssAssetsPlugin({
    assetNameRegExp: /main\..*\.css$/g,
    cssProcessor: cssnano,
    cssProcessorOptions: {
      preset: ['advanced', {
        mergeLonghand: false
      }]
    }
  })
```
But it doesn't change the output, the rule is still removed. Shouldn't disabling this rule prevent it from happening?

**Comment by evilebottnawi** [comment]
@bytasv right now now, a lot of work, feel free investigate problem and send PR with fix this bug

**Comment by bytasv** [comment]
I've tried a bunch of different configurations nothing seems to affect the output, maybe it's a whole setup with plugin and cssnano... I didn't figure out. Eventually I decided to go and use `css-loader` with `minimize: true` option and it seems that the resulted output size of the CSS was almost identical to the one outputed with `optimize-css-assets-webpack-plugin` using `cssnano` (interesting)

For now I will use this as it works out of the box, but I will keep an eye on official webpack plugin for cssnano

**Comment by andyjansson** [comment]
Can't reproduce.

**Input**

```css
.ui.secondary.vertical.pointing.menu {
    border-bottom-width: 0px;
    border-right-width: 0.125rem;
    border-right-style: solid;
    border-right-color: rgba(34, 36, 38, 0.15);
}
```

**Output**

```css
.ui.secondary.vertical.pointing.menu{border-bottom-width:0;border-right:.125rem solid rgba(34,36,38,.15)}
```

**Comment by bytasv** [comment]
Here is the [lock file](https://pastebin.com/G3knTCV8)

I do see cssnano with older version being used by the webpack plugin. However I tried modifying cssnano source directly in my node-modules and it logged out string, so it should be using latest version that I've installed and passed to the plugin. I'm now wondering, maybe it picks up wrong dependencies, like broken presets or something like that?

**Comment by andyjansson** [comment]
Closing this for now, seeing as it seems like an outdated dependency.

**Comment by bytasv** [comment]
@evilebottnawi I tried removing yarn.lock file, node_modules, clean yarn cache and do a clean install, however it is still resolving to the wrong version of longhand:
`cssnano-preset-default` is the one which depends on it, however it is a direct dependency of `cssnano` itself.
As I understand it - cssnano points at wrong version of the preset therefore it is a bug, no?
Or can you tell me how can I explicitly point it at a newer version?

**Comment by evilebottnawi** [comment]
@bytasv `yarn cache clean/npm cache clear force` and remove lock file and again install

**Comment by evilebottnawi** [comment]
For next release i will update packages version in presets to avoid this situation

**Comment by bytasv** [comment]
@evilebottnawi ok, I'm feeling really bad now, I think it was an issue with my `dist` folder not being updated properly after clean install, seems to be working well now. Thanks a lot for all the patience ❤️

**Comment by kleinfreund** [comment]
I’m experiencing the same issue and can only resolve it with `mergeLonghand: false`.

```css
.parent {
  --border-width: 1px;
}

.child {
  border: var(--border-width) solid grey;
}
```
Output:

```css
.child {
  border: solid grey;
}
```
