### ISSUE TITLE
mergeLonghand incorrectly merges border

### ISSUE THREAD

**Issue by ZhangYiJiang** [cssnano/cssnano#557]
Reproduced using just the default preset

```css
.a {
    border: 1px solid #d3d6db;
    border: 1px solid var(--gray-lighter);
    border-left-width: 0;
}
```

gets turned into 

```css
.a{border:1px solid #d3d6db;border-left-width:0}
```

The `border` in the middle is gone. This is an incorrect transformation. This does not happen if `mergeLonghand` is disabled. 

Reproduced on 4.0.0 and 4.0.3. Does not reproduce in 3.10.0
