### ISSUE TITLE
border-width custom property is dropped from border shorthand

### ISSUE THREAD

**Issue by kleinfreund** [cssnano/cssnano#561]
**`test.js`**:

```js
const postcss = require('postcss');
const cssnano = require('cssnano');
const fs = require('fs');

fs.readFile('input.css', (err, css) => {
  postcss([ cssnano({ preset: 'default' }) ])
    .process(css, { from: 'input.css', to: 'output.css' })
    .then(result => {
      fs.writeFile('output.css', result.css, () => true);
    });
});
```

**`input.css`**:

```css
:root {
  --border-width: 1px;
}

.child {
  border: var(--border-width) solid grey;
}
```

Actual **`output.css`**:

```css
:root{--border-width:1px}.child{border:solid grey}
```

Expected **`output.css`**:

```css
:root{--border-width:1px}.child{border:var(--border-width) solid grey}
```

Versions:

- postcss 7.0.1
- cssnano 4.0.3

Similar issues:

- https://github.com/cssnano/cssnano/issues/550
- https://github.com/cssnano/cssnano/issues/556

Workaround:

```js
{
  preset: [
    'default',
    { mergeLonghand: false }
  ]
}
```
