### ISSUE TITLE
Minification removes <width> of border rule if it's a CSS Variable

### ISSUE THREAD

**Issue by oriSomething** [cssnano/cssnano#564]
before:
```css
.button {
  border: var(--border-width) solid var(--border-color);
}
```

after:
```css
.button{border:solid var(--border-color)}
```

As you can see, the `var(--border-width)` part is gone.

The repo for the bug reproduction: [link](https://github.com/oriSomething/css-nano-bug/commit/e4c5d1c9b2020552edc2dc35da2c18fc4c2e53a7)

More details: You might not see `cssnano` as a direct dependency. But `optimize-css-assets-webpack-plugin` uses `cssnano` latest version for the minification
