### ISSUE TITLE
::after content breaks because quotes are being encoded

### ISSUE THREAD

**Issue by actuallymentor** [cssnano/cssnano#568]
Hello!

Thanks so much for this wonderful package, it makes my life a lot easier :)

I'm running into an issue where:

```css
.thing:after {
  content: 'bob';
}
```

Is being nanofied to:

``` css
.thing{content:&quot;bob&quot;}
```

Am I misconfiguring cssnano of does this quality as a bug?

**Comment by evilebottnawi** [comment]
@actuallymentor looks like a bug, what version `cssnano` you use?

**Comment by actuallymentor** [comment]
I'm using `4.0.2`.

**Comment by actuallymentor** [comment]
I just updated to `4.0.4`, the issue still persists.

**Comment by andyjansson** [comment]
I can't replicate. 

**Input**

```css
.thing:after {
  content: 'bob';
}
```

**Output**

```css
.thing:after{content:"bob"}
```
