### ISSUE TITLE
Feature: Order animation values

### ISSUE THREAD

**Issue by ben-mckernan** [cssnano/cssnano#574]
Add support for ordering animation values to `postcss-ordered-values`

Input:
```css
.case-1 {
  animation: linear 1s 2s 3 bounce;
}

.case-2 {
  animation: bounce 3 1s linear 2s;
}
```

Output:
```css
.case-1 {
  animation: bounce 1s linear 2s 3;
}

.case-2 {
  animation: bounce 1s linear 2s 3;
}
```
