### ISSUE TITLE
Parse Error on "calc(env(safe-area-inset-bottom) * 3)"

### ISSUE THREAD

**Issue by MarvinXu** [cssnano/cssnano#578]
cssnano version: latest(4.0.5)
(I used to use version cssnano@3.10.0, and it works fine)

my css code:
```css
@supports (height: env(safe-area-inset-bottom)) {
  .footer {
    padding-bottom: calc(env(safe-area-inset-bottom) * 3) !important;
  }
}
```
error msg:
![image](https://user-images.githubusercontent.com/7382357/43777243-bf732e72-9a84-11e8-8a09-cdffdfee86cc.png)
