### ISSUE TITLE
Invalid CSS output when combining border:none and border-color

### ISSUE THREAD

**Issue by albertxing** [cssnano/cssnano#579]
**Input:**
```css
.test {
  border-bottom: none;
  border-color: red;
}
```
**Output:**
```css
.test{border-bottom:none none red;border-left-color:red;border-right-color:red;border-top-color:red}
```
**Expected:**
```css
.test{border-bottom: none;border-color: red}
```

Note: `border-bottom: none none red` is invalid.

And if you replace `border-bottom: none` with `border: none` the output is also invalid:
```css
.test{border:none none red}
```

cssnano version: 4.0.5
