### ISSUE TITLE
Order in css matters

### ISSUE THREAD

**Issue by amatiasq** [cssnano/cssnano#582]
This is the same issue as ben-eb/postcss-discard-duplicates#42. The deduplication plugin is removing the first instance of a rule, and leaving the second one. This can lead to unexpected side effects.

[This PR](https://github.com/ben-eb/postcss-discard-duplicates/pull/44) is created to solve this issue, if you agree with the solution I can adapt that PR to this project.

**Comment by andyjansson** [comment]
I'm sorry, but the issue is invalid. The current behaviour is correct and this is how the cascade in CSS works. You can view the behaviour on codepen: https://codepen.io/anon/pen/mjogaM

If you're including the same stylesheet over and over, and you're worried about cascading styles, then you should be using a bundler such as webpack.

**Comment by amatiasq** [comment]
I think there was a misunderstanding here. I am using Webpack with SASS.

SASS is processing two files: `a.scss` and `b.scss`

```scss
// a.scss
@import "c.scss";
.a { background-color: red }
```

```scss
// b.scss
@import "c.scss";
.b { background-color: blue }
```

```scss
// c.scss
.c { background-color: green }
```

And the HTML has an element:

```html
<div class="c a">
```

The expected style for the `div` is `background-color: red` but SASS is resolving the imports of `a.scss` and `b.scss` and [`MiniCssExtractPlugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) concatenates them in a single file that contains:

```css
.c { background-color: green }
.a { background-color: red }
.c { background-color: green }
.b { background-color: blue }
```

So the generated output is 

```css
.a { background-color: red }
.c { background-color: green }
.b { background-color: blue }
```

In cases like this the rule removed on deduplication should not be the first ones but the latter ones.

The PR I linked doesn't change the behavior, it adds an option to support cases like this one too.

**Comment by andyjansson** [comment]
Again, our behaviour is consistent with how CSS works. This is a webpack issue. Please refer to the webpack documentation or ask for assistance in their gitter channel.

**Comment by walkerburgin** [comment]
// Sorry to jump in unsolicited, it just took me a minute to understand this -- maybe this helps somebody else.

I think what @andyjansson is saying is that given this input CSS, the browser will apply a green background color to an element with `class="c a"`, because `c` comes later in the stylesheet and gets [precedence](https://css-tricks.com/precedence-css-order-css-matters/).

```css
.c { background-color: green }
.a { background-color: red }
.c { background-color: green }
.b { background-color: blue }
```

So this output from cssnano is correct: 

```css
.a { background-color: red }
.c { background-color: green }
.b { background-color: blue }
```

... but it doesn't match the author's original intent, which was for `c` to come before both `a` and `b`. Which means that this output from mini-css-extract-plugin is the part that's actually wrong (or at least not intuitive): 

```css
.c { background-color: green }
.a { background-color: red }
.c { background-color: green }
.b { background-color: blue }
```
