### ISSUE TITLE
Bug when compressing `border` properties

### ISSUE THREAD

**Issue by afgomez** [cssnano/cssnano#591]
In the latest stable version (4.0.5) there's a bug when merging `border` properties:

Consider the following block:
```css
.class {
  border-top: 1px solid red;
  border-bottom: 1px dashed blue;
  border-right: 10px double green;
  border-left: none; /* Note the `none` */
}
``` 

When pasted into [the playground](https://cssnano.co/playground/) it transforms into:
```css
.class{border-color:red green #00f currentColor;border-style:solid double dashed none;border-width:1px 10px 1px none}
```

The rule `border-width:1px 10px 1px none` is invalid, and makes the browser ignore the other `border-width` values.

<img width="227" alt="screen shot 2018-08-24 at 10 32 57" src="https://user-images.githubusercontent.com/57448/44574395-98294600-a789-11e8-831c-07723d801c68.png">

The expected output should be `border-width:1px 10px 1px 0`.

You can see the issue reproduced in [this codepen](https://codepen.io/afgomez/pen/PdPadL), with the corrected version for comparison.

Thanks!
