### ISSUE TITLE
Reordering of `border-radius` properties in the output breaks the cascade

### ISSUE THREAD

**Issue by afgomez** [cssnano/cssnano#592]
Hi!

Latest stable (4.1.0) seems to change the order of certain properties, breaking the cascade.

Consider this CSS:

```css
.class {
  border-radius: 10px;
  border-bottom-left-radius: 0;
}
```

When pasted in the [playground](https://cssnano.co/playground/), it minimizes as:
```css
.class{border-bottom-left-radius:0;border-radius:10px}
```

The shorthand `border-radius` overrides the specific `border-bottom-left-radius` ([demo](https://codepen.io/afgomez/pen/OoNxww)).

<img width="259" alt="screen shot 2018-08-27 at 12 18 53" src="https://user-images.githubusercontent.com/57448/44654848-6b786700-a9f3-11e8-8e09-0c7a5004cc7c.png">

Thanks!
