### ISSUE TITLE
throw error in postcss-merge-longhand

### ISSUE THREAD

**Issue by evilebottnawi** [cssnano/cssnano#618]
Input:
```css
a {
  border: 1px solid #3060b1;
  border-bottom: 1px solid #3060b1 !important;
}
```
