### ISSUE TITLE
Remove whitespace inside calc()

### ISSUE THREAD

**Issue by valtlai** [cssnano/cssnano#625]
If I have code like this
```css
.foo {
   font-size: calc(var(--h) * 1em);
   margin-top: calc(1.5em / var(--h));
}
```

it can be minified to
```css
.foo{font-size:calc(var(--h)*1em);margin-top:calc(1.5em/var(--h))}
```

but it gets minified to
```css
.foo{font-size:calc(var(--h) * 1em);margin-top:calc(1.5em / var(--h))}
```

So could cssnano remove whitespace around `*` or `/` inside `calc()`?

It’s allowed by [the spec](https://drafts.csswg.org/css-values-3/#calc-syntax):

> white space is required on both sides of the ‘+’ and ‘-’ operators. (The ‘*’ and ‘/’ operaters can be used without white space around them.)

-----
If I have code like this
```css
.foo {
  --a: calc(var(--x, 1) * 10vw);
  --b: var(--x, 1);
}
```

it gets minified to
```css
.foo{--a:calc(var(--x, 1) * 10vw);--b:var(--x,1)}
```

So the space after the comma is not removed inside `calc()`, but is outside `calc()`.
