### ISSUE TITLE
Remove whitespace between @media and parenthesis

### ISSUE THREAD

**Issue by valtlai** [cssnano/cssnano#626]
If I have code like this
```css
@media (min-width: 21rem) {
  --x: y;
}
```

It can be minified to
```css
@media(min-width:21rem){--x:y}
```

But it gets minified to

```css
@media (min-width:21rem){--x:y}
```

Could whitespace after `@media` and before opening parenthesis `(` be removed?
