### ISSUE TITLE
Whitespace is not removed inside calc()

### ISSUE THREAD

**Issue by valtlai** [cssnano/cssnano#627]
If I have code like this
```css
.foo {
  --a: calc(var(--x, 1) * 10vw);
  --b: var(--x, 1);
}
```

it gets minified to
```css
.foo{--a:calc(var(--x, 1) * 10vw);--b:var(--x,1)}
```

So the space after the comma is not removed inside `calc()`, but is outside `calc()`.
