### ISSUE TITLE
Parentheses inside calc are removed

### ISSUE THREAD

**Issue by GrimLink** [cssnano/cssnano#628]
When I run CSSNano my nested calc's are trimmed.

```css
.class {
  // Original
  padding-top: calc(100% / (var(--aspect-ratio, 16/9)));
  // After Nano
  padding-top: calc(100% / var(--aspect-ratio, 16/9));
}
```
Disabling the calc plugin did not help.
So was expecting some other plugin was doing this.
But I can not find which one.

If it is not an plugin than at least give an option to prevent this use case.

**Comment by andyjansson** [comment]
>When I run CSSNano my nested calc's are trimmed.

This is intended behaviour. Why is this an issue? 

>Disabling the calc plugin did not help.

I just tested disabling the plugin, it works fine: 

```js
preset: [
    'default',
    {
        calc: false
    }
]
```

**Input**:

```css
.test {
    padding-top: calc(100% / (var(--aspect-ratio, 16/9)));
}
```

**Output**:

```css
.test{padding-top:calc(100% / (var(--aspect-ratio, 16/9)))}
```

**Comment by GrimLink** [comment]
@andyjansson sorry 😅
I somehow managed to put it outside the default config, directly in preset.
Stupid me.

**Comment by abstractvector** [comment]
Can we reopen this issue as a very specific use case please?

I am able to reproduce the initial report, that the following two CSS styles produce different outputs (confirmed in Chrome 80 and Firefox 74 on Mac OS 10.15.3):

```css
padding-bottom: calc(100% / (var(--aspect-ratio)));
```
Computed: `padding-bottom: 276.906px` (correct)

<img width="656" alt="Screen Shot 2020-03-27 at 8 05 44 AM" src="https://user-images.githubusercontent.com/726531/77770049-e35ca800-7001-11ea-8c4a-9c4ad6b9280e.png">

```css
padding-bottom: calc(100% / var(--aspect-ratio));
```
Computed: `padding-bottom: 0px` (incorrect)

<img width="656" alt="Screen Shot 2020-03-27 at 8 05 28 AM" src="https://user-images.githubusercontent.com/726531/77770038-dfc92100-7001-11ea-941f-00ce9743c457.png">

As per your suggestion in https://github.com/cssnano/cssnano/issues/628#issuecomment-427660027, disabling the `calc` optimization does solve this, but also disables other benefits of the optimization.

I'm not sure why the parentheses matter in this situation, but the empirical evidence suggests they do. I suggest therefore the calc optimization should *not* remove these parentheses.

**Comment by anikethsaha** [comment]
This is an issue with [postcss-calc](https://github.com/postcss/postcss-calc) (`upstream`)

Can you submit this in that repo ?

Thanks

**Comment by abstractvector** [comment]
I've just looked at their issue tracker and it looks like a known issue (https://github.com/postcss/postcss-calc/issues/91). Thanks for pointing me in the right direction.

I'll add more details there.

**Comment by GrimLink** [comment]
@abstractvector you can do the calc almost the same by using `*`.
This fixes the issue and allows you to use the calc minifier.

My code;
```css
.aspect-ratio {
    --aspect-ratio: 16*9;
    position: relative;
    display: block;
    width: 100%;
    overflow: hidden;

    &::before {
        content: "";
        display: block;
        padding-top: calc(100% / var(--aspect-ratio));
    }
}
```
