### ISSUE TITLE
postcss-normalize-whitespace breaks the sourcemap

### ISSUE THREAD

**Issue by andreymal** [cssnano/cssnano#629]
Example (you can download it [here](https://home.andreymal.org/files/postcss_test2.zip)):

```
postcss_test2/
- build/
  - main.css
  - main.css.map
- src/
  - foo/
    - fooindex.css
    - vars.css
  - index.css
- package.json
- postcss.config.js
```

**Build command:** `postcss src/index.css -o build/main.css --map`

**postcss.config.js**

```javascript
module.exports = (ctx) => ({
  map: ctx.options.map,
  plugins: [
    require('postcss-import')(),
    require('postcss-normalize-whitespace')(),
  ]
})
```

**src/index.css**

```css
@import 'foo/fooindex.css';

* {
    box-sizing: border-box;
}
```

**src/foo/fooindex.css**

```css
@import './vars.css';

html, body {
    font-family: sans-serif;
}

.logo1 {
    width: calc(var(--somevar) * 2);
}

* {
    margin: 0;
    padding: 0;
}
```

**src/foo/vars.css**

```css
:root {
    --somevar: 100px * 2;
}
```

When the postcss-normalize-whitespace plugin is disabled, here is the correct sourcemap (Chromium and Firefox):

![](https://i.imgur.com/YYPCjsR.png)

But when I enable it:

![](https://i.imgur.com/5SxBRGo.png)
