### ISSUE TITLE
[postcss-colormin] missing pass through options to colormin

### ISSUE THREAD

**Issue by Swiftwork** [cssnano/cssnano#630]
Tried to avoid making a duplicate issue, but couldn't find anything referencing this issue. Noticed that out IE10 site was having issues in production, due to using cssnano. More specifically colormin was converting `rgba(0,0,0,0)` to `transparent`. Colormin has an option to avoid this called legacy. However it doesn't seem postcss-colormin passes these options through to colormin library alternatively cssnano blocks this.

**Relevant packages**
[colormin](https://github.com/ben-eb/colormin)
[postcss-colormin](https://github.com/cssnano/cssnano/tree/master/packages/postcss-colormin)

**Edit:** config and example

```css
/* Input */
p {
  color: rgba(0, 0, 0, 0);
}
```

```javascript
/* Config */
module.exports = {
    plugins: [
        require('cssnano')({
            preset: ['default', {
                colormin: { legacy: true },
            }],
        }),
    ],
};
```

```css
/* Output */
p {
  color: transparent;
}
```

```css
/* Expected */
p {
  color: rgba(0, 0, 0, 0);
}
```

`transparent ≠ rgba(0, 0, 0, 0)` [first is browser interpretation, second is color calculation.](https://stackoverflow.com/questions/32479188/whats-the-difference-between-rgba0-0-0-0-and-transparent)

Kind regards and great work
Erik Hughes
