### ISSUE TITLE
Support gradient color stop double-position syntax

### ISSUE THREAD

**Issue by valtlai** [cssnano/cssnano#650]
I have a CSS gradient with double-position color stops, like this:

```css
.foo {
   background: repeating-linear-gradient(45deg, #eee 0 3px, #fff 3px 6px);
}
```

After minification it looks like:

```css
.foo{background:repeating-linear-gradient(45deg,#eee 3px,#fff 3px 6px)}
```

The first color stop position, `0`, is removed which breaks the gradient.

**Comment by andyjansson** [comment]
The source gradient isn't valid.

**Comment by valtlai** [comment]
@andyjansson Can you elaborate? This syntax is specified in [css-images-4](https://drafts.csswg.org/css-images-4/#color-stop-syntax) spec and it’s [supported](https://www.chromestatus.com/feature/5712111258828800) by Chrome&nbsp;≥&nbsp;71.

**Comment by andyjansson** [comment]
Oh, ok. So this is an updated syntax draft which isn't supported in any yet-released browser. All current browsers report it as an invalid property value.

**Comment by valtlai** [comment]
This syntax is now [supported](https://caniuse.com/#feat=mdn-css_types_image_gradient_linear-gradient_doubleposition) by most of the major browsers, except IE and pre-Chromium Edge.

**Comment by msteller-connyun** [comment]
I’ve the same issue.
Is there a workaround?

Tried to disable different options, without success.

**Comment by fishintaiwan** [comment]
Currently working around this by using a very small decimal value for the first color stop.

```css
.foo {
   background: repeating-linear-gradient(45deg, #eee 0.0001px 3px, #fff 3px 6px);
}
```
