### ISSUE TITLE
CSS variables + border generate wrong output

### ISSUE THREAD

**Issue by manucorporat** [cssnano/cssnano#652]
A picture is worth a thousand words:
<img width="1259" alt="screenshot 2018-10-31 at 19 47 09" src="https://user-images.githubusercontent.com/127379/47811688-a6c24980-dd46-11e8-9e83-0ec729a35ecc.png">

```css 
.class {
  border-width: var(--border-width);
  border-style: var(--border-style);
  border-color: var(--btn-border-color);
}
```

generates:
```
.class{border: none}
```

which is clearly wrong
