### ISSUE TITLE
mergeLonghand works incorrectly with border-image

### ISSUE THREAD

**Issue by twop** [cssnano/cssnano#656]
cssnano v 4.1.7

```css
.style {
    border-image: linear-gradient(to right, rgba(230, 232, 235, 0), #e6e8eb) 0 0
        0 100%;
    border-left: 60px;
    border-top: 0;
    border-right: 0;
    border-bottom: 0;
}
```

is translated to 
```css
.style {
    border-image: linear-gradient(90deg, rgba(230, 232, 235, 0), #e6e8eb) 0 0 0
        100%;
    border: 0;
    border-left: 60px;
}
```
Which seems to be incorrect according to mdn: 
https://developer.mozilla.org/en-US/docs/Web/CSS/border

> The border CSS property sets an element's border. It's a shorthand for border-width, border-style, and border-color.
>  As with all shorthand properties, any omitted sub-values will be set to their initial value. Importantly, border cannot be used to specify a custom value for border-image, but instead sets it to its initial value, i.e., none.

+ I was unable to repro the issue in the playground

**Comment by andyjansson** [comment]
I've completely missed the fact that `border` does this. It's weird that it's declared as a shorthand for `border-width`, `border-style` and `border-color`, yet manipulates `border-image` which it has no direct or indirect connection to. 

Thanks for the heads-up. For now, you can probably fix it locally by simply moving the declaration down to the bottom of the rule.

Regarding adding this to the `mergeLonghand`, is it fine to just relocate `border-image` below `border` in every case, or do we forsee any issues with that approach?

**Comment by twop** [comment]
I'm not a css expert, so my opinion might not be as valuable.

My concern is this situation

```css
.style-img {
    border-image: linear-gradient(90deg, rgba(230, 232, 235, 0), #e6e8eb) 0 0 0
        100%;
}

.style-brd-bad {
    border: 0;
    border-left: 60px;
}

.style-brd-good {
    border-left: 60px;
    border-top: 0;
    border-right: 0;
    border-bottom: 0;
}
```

```html
<h1>
  that is fine
  <div class="style-img style-brd-good"/>
</h1>

<h1>
  this would cause the same issue
  <div class="style-img style-brd-bad"/>
</h1>
```

So I would suggest not to merge into border property (if it not already present). Even with reordering I wouldn't feel safe to enable that optimization on our project
