### ISSUE TITLE
`background-color: transparent` not working

### ISSUE THREAD

**Issue by ClementParis016** [cssnano/cssnano#666]
I have an issue with a `background-color` not working after a pass through cssnano, it seems like an issue with the way how selectors are combined together (but honestly I don't know much about how cssnano works).

You can reproduce the issue in the [playground](https://cssnano.co/playground/) (in v4.1.7, which is the same my code is using locally) by entering the following CSS code as input:

<details>
  <summary>Input CSS</summary>
  
```css
@charset "UTF-8";

.Button--frameless {
  color: #9090A3;
  background-color: transparent;
  -webkit-transition: background-color 0.15s ease;
  transition: background-color 0.15s ease;
  border: none;
}

.Button--frameless:not([disabled]):not(.Button--primary.Button--is-loading):hover {
  background-color: transparent;
}

.Button--frameless-light {
  color: #FFF;
  background-color: transparent;
  -webkit-transition: background-color 0.15s ease;
  transition: background-color 0.15s ease;
  border: none;
}

.Button--frameless-light:not([disabled]):not(.Button--primary.Button--is-loading):hover {
  background-color: transparent;
}
```
</details>

Which produces the following output (unminified for readability):

<details>
  <summary>Output CSS</summary>
  
```css
.Button--frameless {
  color: #9090a3;
  -webkit-transition: background-color 0.15s ease;
  transition: background-color 0.15s ease;
  border: none;
}
.Button--frameless,
.Button--frameless-light,
.Button--frameless:not([disabled]):not(.Button--primary.Button--is-loading):hover {
  background-color: transparent;
}
.Button--frameless-light {
  color: #fff;
  -webkit-transition: background-color 0.15s ease;
  transition: background-color 0.15s ease;
  border: none;
}
.Button--frameless-light:not([disabled]):not(.Button--primary.Button--is-loading):hover {
  background-color: transparent;
}
```
</details>

You can see in the input CSS that the `.Button--frameless` and `.Button--frameless-light` have a `background-color: transparent`  which is combined with other selectors in the output. But for an unknown reason, when these styles are applied, the button is not transparent and the rule seems to not be working, it doesn't even appear in the Inspector.
