### ISSUE TITLE
Combination of border: none and border-left: solid results in incorrect border properties

### ISSUE THREAD

**Issue by rgoj** [cssnano/cssnano#668]
With cssnano 4.1.7, I'm getting problems with `border: none` not being interpreted correctly. I can work around this by using `border: 0`.

The following:

```css
button {
    color: blue;
    border: none;
    border-left: solid;
    border-color: grey;
    border-width: 2px;
}
```

results in:

```css
.search__button{
    color: #00f;
    border: 2px grey;
    border-left: solid
}
```
and the left border appears in blue rather than grey as intended.

If I change `border: none;` to `border: 0;`, i.e.:

```css
button {
        color: blue;
        border: 0;
        border-left: solid;
        border-color: grey;
        border-width: 2px;
    }
```

the resulting CSS works correctly (the left border is grey and 2px wide):

```css
button {
    color: #00f;
    border: 0;
    border-left: solid;
    border-color: grey;
    border-width: 2px
}
```
