### ISSUE TITLE
reduce-transforms in animation @keyframes 

### ISSUE THREAD

**Issue by impressioncr** [cssnano/cssnano#674]
That a keyframe was reduce-transformed when opacity property existed resulted in that animation didn't work on ios.

> input

```css
@keyframes bubbleScale {
    0% {
      transform: scale3D(1, 1, 1);
    }
    99% {
      transform: scale3d(2, 2, 2);
    }
    100% {
      transform: scale3D(0, 0, 0);
      opacity: 0;
    }
}
```

> output

```css
@keyframes bubbleScale {
    0% {
      transform: scaleX(1);
    }
    99% {
      transform: scale3d(2, 2, 2);
    }
    100% {
      transform: scale3D(0, 0, 0);
      opacity: 0;
    }
}
```
[online demo](https://codepen.io/impressioncr/pen/MZLGqE)

**Comment by evilebottnawi** [comment]
@impressioncr looks like bug, feel free to send a PR with fix

**Comment by impressioncr** [comment]
Found out that `scale3D(0, 0, 0)` couldn't work with `opacity: 0` on ios.

Fixed with 
```css
@keyframes bubbleScale {
    0% {
      transform: scaleX(1);
    }
    99% {
      transform: scale3d(2, 2, 2);
    }
    100% {
      opacity: 0;
    }
}
```
reduceTransforms optimisation is fine yet transforming keyframes values is unsafe anyway.
