### ISSUE TITLE
mergeLonghand is unsafe with border and CSS variables

### ISSUE THREAD

**Issue by manucorporat** [cssnano/cssnano#675]
Using  4.1.8 (#671)

Input:
```css
.class {
  --border-width: 0 0 0 1px;
  --border-style: solid;
  --border-color: black;
  
  border-width: var(--border-width);
  border-style: var(--border-style);
  border-color: var(--border-color);
}
```

output:

```css
.class{
--border-width:0 0 0 1px;--border-style:solid;--border-color:#000;
border:var(--border-width) var(--border-style) var(--border-color)
}
```

Notice the generates CSS is not equivalent since border-width can take values like:

```css
border-width: 0 0 0 1px;  /* style bottom border */
```

leading a computed value of `border`:

```css
border: 0 0 0 1px solid black;
```
which is NOT valid.

**Expected behaviour:**

Do not merge border into a shortcut when using CSS variables.

Using the playground

<img width="1512" alt="screenshot 2019-01-15 at 17 58 33" src="https://user-images.githubusercontent.com/127379/51196460-74f56380-18ef-11e9-8706-55333c8c951b.png">

**Comment by evilebottnawi** [comment]
@manucorporat Can't find any documentation what css variables supports multiple values

**Comment by manucorporat** [comment]
yep, border seems too complicated to handle when CSS variables are used. 

We just reenabled this optimization, but seems like we have to disable it again :(
https://github.com/ionic-team/stencil/commit/cbd357926ec98d1b6a310352b4d2496c37d34adb

Happy to help, but I am not very familiarised with the css-nano codebase, where should I look into?

**Comment by manucorporat** [comment]
I gave it a try, but I fall down the rabbit hole without results. I guess we'll just deactivate this optimization again

**Comment by sdvg** [comment]
Similar issue with `font`:

```
--font-size: 1rem;

body {
  font: var(--font-size) sans-serif;
}
```

becomes

```
--font-size:1rem;body{font:var(--font-size),sans-serif}
```

(the comma should be a space)

Please tell if I should create a new issue, but I think this is the same problem.

**Comment by evilebottnawi** [comment]
@sdvg yep, it is other issue, i think we need create new issue

**Comment by kingback** [comment]
here's another case:

input

```css
div {
  height: constant(safe-area-inset-bottom);
  height: env(safe-area-inset-bottom);
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
}
```

output

```css
div{
  height:constant(safe-area-inset-bottom);
  height:env(safe-area-inset-bottom);
  padding-bottom:env(safe-area-inset-bottom);
}
```

`height/width` is ok, but `padding/margin` is broken

expected

```css
div {
  height: constant(safe-area-inset-bottom);
  height: env(safe-area-inset-bottom);
  padding-bottom: constant(safe-area-inset-bottom);
  padding-bottom: env(safe-area-inset-bottom);
}
```

postcss.config.js

```js
module.exports = {
  plugins: [
      require('cssnano')({
          preset: ['default', {
            // mergeLonghand: false
          }], 
      }),
  ],
};
```

it works right if set `mergeLonghand` option to `false`

**Comment by evilebottnawi** [comment]
@kingback should be easy to fix, feel free to send a PR

**Comment by pcasaretto** [comment]
Hi everyone. I think this just bit in production. Is there any workaround aside from not using variables?

**Comment by evilebottnawi** [comment]
https://github.com/cssnano/cssnano/issues/675#issuecomment-471985097

**Comment by pcasaretto** [comment]
😓 sorry

**Comment by evilebottnawi** [comment]
You can send a PR with fix

**Comment by pcasaretto** [comment]
If I understand correctly, this test:
```javascript
test(
  'Should correctly merge borders with custom properties (#652)',
  processCSS(
    'h1{border-width:var(--a);border-style:var(--b);border-color:var(--c)}',
    'h1{border:var(--a) var(--b) var(--c)}'
  )
);
```

Should change to a `passthroughCSS`. Right?

**Comment by hetgelaat** [comment]
Not sure if this is related, but I noticed that this:
`border: solid 2px var(--buttonBorderColor, var(--buttonBaseColor, #000));`
Turns into 
`border: 2px solid var(--buttonbordercolor,var(--buttonBaseColor,#000));`
Notice the missing camelCasing in the generated outcome.

**Comment by megapctr** [comment]
nuxt users can add this to `nuxt.config.js` until the issue is resolved
```js
  build: {
    postcss: {
      plugins: {
        'postcss-import': {},
        'postcss-nested': {},
        cssnano: {
          preset: ['default', {
            mergeLonghand: false,
          }],
        },
      },
    },
  },
```

**Comment by alexreardon** [comment]
I am not sure if this is related: https://github.com/parcel-bundler/parcel/issues/5290 but it looks to be a similar issue

```css
html {
	--local-slim-width: 2px;
	
	border-style: solid;
	border-color: rgba(255, 255, 255, var(--header-line-opacity));
	border-top-width: 0px;
	border-right-width: var(--local-slim-width);
	border-bottom-width: 3px;
	border-left-width: 2px;
}
```

**Comment by dimti** [comment]
Example with `border-width` in webpack with css-minimizer-webpuck-plugin
  
  Me closed issue with has not relate with minimizer plugin https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/59 and maintainer tell me for go me to cssnano issues.

- Operating System: Linux 5.10
- Node Version: v10.23.2
- NPM Version: 6.14.11
- webpack Version: 5.23.0
- css-minimizer-webpack-plugin Version: ^1.2.0

I try to optimize some border options and use of border-width with two values: `border-width: 13px 6px;`
cssnano (css-minimizer-webpack-plugin) showed me strange and incorrect result: `border-width: 13 6px 6px;`

That strange optimization work only with exists all of three style-rules: `border-width`, `border-style`, `border-right-color`

Source:
```css
div {
    border-width: 13px 6px;
    border-style: solid;
    border-right-color: transparent;
}
```

### Expected Behavior

```css
div{border-width:13px 6px;border-right:6px transparent;border-style:solid}
```

### Actual Behavior

```css
div{border-width:13px 6px 6px;border-right:6px transparent;border-style:solid}
```

### Code

https://gist.github.com/dimti/468b3793ec81d7c5b1f0f1e1669c2eb1

### How Do We Reproduce?

Source styles:

```css
div {
    border-width: 13px 6px;
    border-style: solid;
    border-right-color: transparent;
}
```

I set `horizontal` padding to `13px` and `vertical` padding to `6px` with appropriate this tutorial https://developer.mozilla.org/ru/docs/Web/CSS/border-width#%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81

Compiled data without optimizations - show me correct result: `border-width: 13px 6px;`

With optimization i'm have incorrect result: `border-width: 13px 6px 6px;`
