### ISSUE TITLE
mergeRules when combined with mergeLonghand can create the wrong rules

### ISSUE THREAD

**Issue by adamwathan** [cssnano/cssnano#701]
Apologies for not being able to reduce this to the absolute minimum reproduction, but given this CSS:

```css
.has-errors .input {
  background-color: #fcebea;
  border-color: #cc1f1a;
}

.has-errors .checkbox-label {
  background-color: #fcebea;
  border-color: #cc1f1a;
}

.has-errors .checkbox-inline {
  background-color: #fcebea;
  border-color: #cc1f1a;
}

.error-banner .field-errors.filled {
  width: 100%;
  padding: 1.5rem 1.5rem 1rem;
  background-color: #fcebea;
  border-bottom-width: 1px;
  border-style: solid;
  border-color: #cc1f1a;
}

.error-banner .field-errors.filled   .field-error {
  width: 100%;
  font-size: .875rem;
  color: #22292f;
  line-height: 1.5;
  margin-bottom: .5rem;
}
```

When minified with mergeRules and mergeLonghand both enabled, the output is:

```css
.error-banner .field-errors.filled,
.has-errors .checkbox-inline,
.has-errors .checkbox-label,
.has-errors .input {
    background-color: #fcebea;
    border-color: #cc1f1a
}

.error-banner .field-errors.filled {
    width: 100%;
    padding: 1.5rem 1.5rem 1rem;
    border-bottom: 1px;
    border-style: solid
}

.error-banner .field-errors.filled .field-error {
    width: 100%;
    font-size: .875rem;
    color: #22292f;
    line-height: 1.5;
    margin-bottom: .5rem
}
```

The important changes here are that the `border-color` declarations were grouped and the `border-color` declaration from the `.error-banner .field-errors.filled` selector was removed, and that what was originally `border-bottom-width: 1px` is simplified to `border-bottom: 1px`.

But because the `border-color` declaration was hoisted to the group at the top, the border color no longer takes effect for the `.error-banner .field-errors.filled` selector because `border-bottom: 1px` sets a default color of `black` which overrides it.

This sort of hand-crafted diff tries to make the important changes clear:

```diff
+ .error-banner .field-errors.filled,
  .has-errors .checkbox-inline,
  .has-errors .checkbox-label,
  .has-errors .input {
      background-color: #fcebea;
      border-color: #cc1f1a
  }
  
  .error-banner .field-errors.filled {
      width: 100%;
      padding: 1.5rem 1.5rem 1rem;
-     border-bottom-width: 1px;
+     border-bottom: 1px;
      border-style: solid
-     border-color: #cc1f1a
  }
  
  .error-banner .field-errors.filled .field-error {
      width: 100%;
      font-size: .875rem;
      color: #22292f;
      line-height: 1.5;
      margin-bottom: .5rem
  }
```

In this case the expected behavior is that because `border-color` was hoisted out, `border-bottom-width` cannot be simplified to `border-bottom`, or alternatively, the `border-color` declaration should not be removed from that selector at all.

Tricky stuff to get right for sure, I don't envy anyone trying to build a tool like this but am extremely grateful for your hard work 👍

**Comment by evilebottnawi** [comment]
Oh, can we reduce example? I think problem in `postcss-merge-longhand`, he runs before `postcss-merge-rules` and create invalid border values so we have invalid merge rules

**Comment by evilebottnawi** [comment]
To be honestly, i don't have enough time and funds :disappointed:  to works a lot of time on this so feel free to send a PR

**Comment by adamwathan** [comment]
Cool thanks I will see if I can get it working and PR something! 👍 

For others, here's the minimum reproduction:

```css
.foo {
  border-color: #cc1f1a;
}

.bar {
  border-bottom-width: 1px;
  border-style: solid;
  border-color: #cc1f1a;
}
```

Compiles to:

```css
.bar,
.foo {
    border-color: #cc1f1a
}

.bar {
    border-bottom: 1px;
    border-style: solid
}
```

This is related but possibly a different issue, but this CSS:

```css
.foo {
  border-color: #cc1f1a;
}

.bar {
  border-bottom: 1px;
  border-color: #cc1f1a;
}
```

...compiles to:

```css
.bar,
.foo {
    border-color: #cc1f1a
}

.bar {
    border-bottom: 1px
}
```

...which is also wrong, since it's important that the `border-color` declaration comes after `border-bottom` for the color to take affect.

**Comment by evilebottnawi** [comment]
@adamwathan Can you provide what your expected too for other developers?

**Comment by adamwathan** [comment]
Added expected behavior to the comment 👍

**Comment by tmorehouse** [comment]
I am seeing a similar issue (which may be related) when using the default preset:

```css
  background-position: center right calc(0.375em + 0.1875rem);
```

is being converted to:

```css
  background-position: 100% right calc(0.375em + 0.1875rem)
```

which does not produce the same result visually.

**Comment by evilebottnawi** [comment]
@tmorehouse not related to this issue

**Comment by clshortfuse** [comment]
With PR #723 , the output for the first comment would be

````
.has-errors .input,
.has-errors .checkbox-label,
.has-errors .checkbox-inline {
  background-color: #fcebea;
  border-color: #cc1f1a;
}

.error-banner .field-errors.filled {
  width: 100%;
  padding: 1.5rem 1.5rem 1rem;
  background-color: #fcebea;
  border-bottom-width: 1px;
  border-style: solid;
  border-color: #cc1f1a;
}

.error-banner .field-errors.filled .field-error {
  width: 100%;
  font-size: .875rem;
  color: #22292f;
  line-height: 1.5;
  margin-bottom: .5rem;
}
````

At I glance, I think that's right. It also outputs:

````
.foo {
  border-color: #cc1f1a;
}

.bar {
  border-bottom-width: 1px;
  border-style: solid;
  border-color: #cc1f1a;
}
````

Which I believe is as expected in the fourth comment. I'll update the commit message.

**Comment by anikethsaha** [comment]
Input

```css
.foo {
  border-color: #cc1f1a;
}

.bar {
  border-bottom-width: 1px;
  border-style: solid;
  border-color: #cc1f1a;
}

```


With `postcss-merge-longhand` only

```css
.foo {
  border-color: #cc1f1a;
}

.bar {
  border-bottom: 1px;
  border-color: #cc1f1a;
  border-style: solid;
}
```


With `postcss-merge-rules` only 

```css
.foo {
  border-color: #cc1f1a;
}

.bar {
  border-bottom-width: 1px;
  border-style: solid;
  border-color: #cc1f1a;
}

```

With `postcss-merge-longhand` before `postcss-merge-rules`

```css
.foo,.bar {
  border-color: #cc1f1a;
}

.bar {
  border-bottom: 1px;
  border-style: solid;
}
```

With `postcss-merge-rules` before `postcss-merge-longhand`

```css
.foo {
  border-color: #cc1f1a;
}

.bar {
  border-bottom: 1px;
  border-color: #cc1f1a;
  border-style: solid;
}

```


Here, both plugins are working fine as independently but not together.
The fix as expected is to have the merging of the rule before merging the longhand!

cc @evilebottnawi !
