### ISSUE TITLE
cssnano mangles background-position property that has calc(...)

### ISSUE THREAD

**Issue by tmorehouse** [cssnano/cssnano#712]
cssnano is mangling certain `background-position` rules:

```css
.foo {
  background-position: center right calc(0.375em + 0.1875rem);
}
```
becomes:
```css
.foo {
  background-position: 100% calc(0.375em + 0.1875rem);
}
```

but when changing the order to:
```css
.foo {
  background-position: right calc(0.375em + 0.1875rem) center;
}
```
it works.

This issue can be reproduiced in the playground at https://cssnano.co/playground/

![image](https://user-images.githubusercontent.com/2781561/52904436-a5883000-3202-11e9-923a-2e213495a1f8.png)

![image](https://user-images.githubusercontent.com/2781561/52904441-b769d300-3202-11e9-9860-58af5ab906f3.png)

While there is a workaround for addressing the issue, the source css is not in our control (Bootstrap V4.3), and requires a rule override in our custom CSS.
