### ISSUE TITLE
mergeRules can change order of properties when it matters

### ISSUE THREAD

**Issue by zipper** [cssnano/cssnano#717]
In some cases, the order of properties is very importatnt, such as with vendor prefixes. See this input:
```css
/**
 * 1. Removes inner shadow in Safari (must not be textfield because of iOS 10)
 * 2. Removes the +- buttons in browsers (will be autoprefixed)
 */
[type="number"] {
	-webkit-appearance:none;   /* 1 */
	appearance:textfield;      /* 2 */
}

/**
 * 1. Removes the cross for emptying the field and removes border-radius in Safari (must not be textfield because of iOS 10)
 */
[type="search"] {
	-webkit-appearance:none; /* 1 */
}
```

It transforms into this (deminified):
```css
[type=number] {
	-moz-appearance:textfield;
	appearance:textfield
}
[type=number],
[type=search] {
	-webkit-appearance:none
}
```

The input first gets autoprefixed using autoprefixer. This step is fine - into the first rule, it adds `-moz-appearance:textfield` and leaves the `-webkit-appearance` untouched. That's all ok. But then cssnano [merges rules by partial declarations](https://github.com/cssnano/cssnano/tree/master/packages/postcss-merge-rules#by-partial-declarations) and that changes the order, so `-webkit` rule is last. That alone is a problem (vendor prefixes should never be last), more over in Firefox 62 it causes the number input to have a spinner buttons, since it kind of understands `-webkit` prefix from this version. Because of the need of different values of `-webkit-appearance` and `appearance`, it has to be in CSS before autoprefixer, otherwise I could just run cssnano before autoprefixer. In this case, it doesn't matter which one of autoprefixer or cssnano runs first.

**Comment by evilebottnawi** [comment]
@zipper what is your order of plugins?

**Comment by zipper** [comment]
It doesn't matter, the output is similar in both cases.

Order autoprefixer -> cssnano:
```css
[type=number]{
	-moz-appearance:textfield;
	appearance:textfield
}
[type=number],
[type=search]{
	-webkit-appearance:none
}
```

Order cssnano -> autoprefixer:
```css
[type=number]{
	-webkit-appearance:textfield;
	-moz-appearance:textfield;
	appearance:textfield
}
[type=number],
[type=search]{
	-webkit-appearance:none
}
```

With autoprefixer off completely:
```css
[type=number]{
	appearance:textfield
}
[type=number],
[type=search]{
	-webkit-appearance:none
}
```

I believe the correct output should be on of these (with autoprefixer on):
```css
[type=number]{
	-webkit-appearance:none;
	-moz-appearance:textfield;
	appearance:textfield
}
[type=search]{
	-webkit-appearance:none
}
```
or
```css
[type=number],
[type=search]{
	-webkit-appearance:none
}
[type=number]{
	-moz-appearance:textfield;
	appearance:textfield
}
```

**Comment by evilebottnawi** [comment]
When we merge selectors, we should respect `prefixes` too, can you describe shortly what you actually have and what you expected for other developers who want to help, thanks!

**Comment by zipper** [comment]
I think it is well described in my previous comment https://github.com/cssnano/cssnano/issues/717#issuecomment-471470238. In short, I need different value for prefixed and unprefixed properties. That means having both in CSS, since autoprefixer prefixes the property, but keeps the value same (well, when they actually are meant to be same). So I split the declaration, let the autoprefixer add `-moz` and that's it. The second rule only needs prefixed property, since it is only Safari targeted. Since those two rules are in some normalize.less directly after each other, they get optimized but order is corrupted. So for input:
```css
/**
 * 1. Removes inner shadow in Safari (must not be textfield because of iOS 10)
 * 2. Removes the +- buttons in browsers (will be autoprefixed)
 */
[type="number"] {
	-webkit-appearance:none;   /* 1 */
	appearance:textfield;      /* 2 */
}

/**
 * 1. Removes the cross for emptying the field and removes border-radius in Safari (must not be textfield because of iOS 10)
 */
[type="search"] {
	-webkit-appearance:none; /* 1 */
}
```

Expected output should be one of these:
```css
[type=number]{
	-webkit-appearance:none;
	-moz-appearance:textfield;
	appearance:textfield
}
[type=search]{
	-webkit-appearance:none
}
```

or

```css
[type=number],
[type=search]{
	-webkit-appearance:none
}
[type=number]{
	-moz-appearance:textfield;
	appearance:textfield
}
```

I temporarily fixed this by turning `mergeRules` off.
