### ISSUE TITLE
Exception with mixed border declarations

### ISSUE THREAD

**Issue by ToadKing** [cssnano/cssnano#718]
```css
.test {
    border: 2px solid transparent;
    border-bottom-width: 0;
    border-right-width: 0;
    border-top-width: 0;
}
```

Trying this in the online REPL spits out a Javascript error: `TypeError: values[i] is undefined`
