### ISSUE TITLE
stop transform transparent to initial when need support for edge

### ISSUE THREAD

**Issue by Austaras** [cssnano/cssnano#721]
tranform
``` css
input[type=range]::-ms-thumb {
  background-color: transparent;
}
```
to
```  css
input[type=range]::-ms-thumb {
  background-color: initial;
}
```
will cause a bug in Edge causing slider thumb unseenable
