### ISSUE TITLE
Should not strip calc(var(--cp)) expressions

### ISSUE THREAD

**Issue by lunelson** [cssnano/cssnano#725]
Currently cssnano assumes that `calc(var(--myvar))` will always be equal to `var(--myvar)` but this is not a safe assumption. `var()` expressions can contain arbitrary numeric expressions, and may *need* a `calc()` wrapper in order to be valid. Example:

```css
p {
  --fz: (4em / 2);
  font-size: calc(var(--fz));
}
```
cssnano will strip this down to the following, which is not valid:
```css
p{--fz:(4em/2);font-size:var(--fz)}
```
