### ISSUE TITLE
mergeRules merges :host(tagname) with tagname 

### ISSUE THREAD

**Issue by MapTo0** [cssnano/cssnano#730]
If we have the following CSS in a custom element's shadow root:

````css
:host(custom-element) {
  width: 200px;
  height: 40px;
  background: red;
}

custom-element {
  width: 200px;
  height: 40px;
  background: red;
}
````

becomes

```css
:host(custom-element),
custom-element {
  width: 200px;
  height: 40px;
  background: red;
}
```

both selectors are getting merged which is not a valid syntax.

**Comment by evilebottnawi** [comment]
It is feature, feel free to send a PR

**Comment by evilebottnawi** [comment]
Also here can be problem, if browser support custom element, but doesn't support `:host`, it is break rule, not sure it is safe

**Comment by MapTo0** [comment]
In this case (which I hope no browser will be built like that 😀) both selectors will just be unused.

**Comment by evilebottnawi** [comment]
Just need ensure what all browsers what supports `custom` elements also supports `:host`

**Comment by evilebottnawi** [comment]
Not sure it is bug, let's test it:

**index.html**

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Host selectors</title>
    <script src="main.js" defer></script>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
  <footer>
    <context-span class="one">Chris Mills</context-span>
    <context-span class="two">Chris Mills</context-span>
  </footer>
  </body>
</html>

```

**style.css**

```css
footer {
  background-color: #ddd;
  padding: 20px;
  margin: 20px 0;
}

```

**main.js**

```js
class ContextSpan extends HTMLElement {
  constructor() {
    super();

    const style = document.createElement('style');
    const span1 = document.createElement('span');
    const h1 = document.createElement('h1');

    span1.textContent = this.textContent;
    h1.textContent = 'Text';

    const shadowRoot = this.attachShadow({ mode: 'open' });

    shadowRoot.appendChild(style);
    shadowRoot.appendChild(span1);
    shadowRoot.appendChild(h1);

    style.textContent = `
        :host(.one), span { color : red; }
      `;
  }
}

// Define the new element
customElements.define('context-span', ContextSpan);
```

In the `one` shadow-host all is red, In the `two` shadow-host only span is `red`.
I use Сhrome `79`.  

Let's change:

```css
:host, h1 { color: blue; }
span { color: red; }
```

All `h1` tags is blue, all `span` tags is red.
All works fine also.



Let's test with `:host-context`:
```js
:host { color: blue; }
:host-context(div), span { color: red; }
```

All is red, except `h1` tag into `.one` shadow-root.
All works fine.

Can't see problem :confused:
