### ISSUE TITLE
Using var(--direction) will break postcss-minify-gradients

### ISSUE THREAD

**Issue by judewang** [cssnano/cssnano#732]
Here's the sample code:

```css
body {
  --direction: top;
  background: linear-gradient(
      to var(--direction),
      transparent,
      black
    )
    0% 50% no-repeat;
}
```

This will get an error like:

```shell
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'length' of undefined
```

Problems may be happened in here, but have no idea how to fix it😅 https://github.com/cssnano/cssnano/blob/8d4610a6391ddab29bcb08ef0522d0b7ce2d6582/packages/postcss-minify-gradients/src/index.js#L24-L27
