### ISSUE TITLE
Minification of border-width loses axis

### ISSUE THREAD

**Issue by holloway** [cssnano/cssnano#733]
Input:
```css
.selector  {
  border-style: solid;
  border-width: 0px 0px 5px 5px;
  border-top-color: transparent;
}
```

Output in CSS Nano 4.1.10 (via playground):

```css
.selector{border-width:0 5px 5px;border-top:0 transparent;border-style:solid}
```

Notice how it's lost one of the axis on `border-width`.
