### ISSUE TITLE
wrong output with calc()

### ISSUE THREAD

**Issue by liuwf2012** [cssnano/cssnano#742]
![image](https://user-images.githubusercontent.com/7323242/56950434-0ff50f00-6b68-11e9-8b70-326cf90eb3c2.png)

### initial state
```css
.class {
  width: calc(-25rem - (1280px - 100vw) * 0.5);
}
```

### correct minimization
```css
.class{
  width: calc(-25rem - 640px + 50vw);
}
```

### actual minimization
```css
.class{
  width: calc(-25rem - 640px - 50vw);
}
```
