### ISSUE TITLE
postcss-merge-longhand breaks on border-width props with !important statements

### ISSUE THREAD

**Issue by przemyslawzalewski** [cssnano/cssnano#743]
Access to `border-width` props within postcss-merge-longhand seems to lack proper guards against missing values, causing the following code to throw `TypeError`.

```css
.x {
  border: 1px solid lightgray !important;
  border-top-width: 0 !important;
  border-right-width: 0 !important;
  border-bottom-width: 0 !important;
}
```

```javascript
TypeError: Cannot read property 'toLowerCase' of undefined
    at /playground/<input css 1>:1
    at /playground/<input css 1>:5
    at phenomic.main.22573732.js:141340
    at mergeRules (phenomic.main.22573732.js:25637)
    at phenomic.main.22573732.js:141333
    at Array.forEach (<anonymous>)
    at phenomic.main.22573732.js:141330
    at phenomic.main.22573732.js:20320
    at phenomic.main.22573732.js:20257
    at Rule.each (phenomic.main.22573732.js:20223)
    at Rule.walk (phenomic.main.22573732.js:20253)
    at Rule.walkDecls (phenomic.main.22573732.js:20318)
```

However, this seems to work but misses the last `!important` statement:

```css
.x {
  border: 1px solid lightgray !important;
  border-top-width: 0 !important;
  border-right-width: 0 !important;
  border-bottom-width: 0;
}
```

The bug doesn't occur when there are all border-width properties present which seem to indicate the root cause:

```css
.x {
  border: 1px solid lightgray !important;
  border-top-width: 0 !important;
  border-right-width: 0 !important;
  border-bottom-width: 0 !important;
  border-left-width: 2px !important;
}
```

Seems to be related to #718
