### ISSUE TITLE
Better handling of exponents

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#752]
I think the conversion functions inside postcss-convert-values need examining again, as exponents can be lost whilst the conversion happens. This is a good thing for some values:

```css
div { margin: 12e1px }
div { margin: 120px }
```

```css
div { margin: 12e3px }
div { margin: 12000px }
```

But for larger values we should keep the exponent:

```css
div { margin: 12e5px }
div { margin: 1200000px }
```

This is likely happening when we do a division by one here: https://github.com/cssnano/cssnano/blob/master/packages/postcss-convert-values/src/lib/convert.js#L34-L53
