### ISSUE TITLE
discardEmpty: empty display defaults to block

### ISSUE THREAD

**Issue by captainfromspace** [cssnano/cssnano#776]
When leaving the `display` property empty, cssnano defaults the value to `block`.

### Preconditions
1. cssnano version: 4.1.10 (or use https://cssnano.co/playground/)

### Steps to reproduce
1. create a selector like below
```css
.cssnano-test {
    display: flex;
}
```
2. Change the display declaration to `display:;`

### Expected result (if using [playground](https://cssnano.co/playground/))
```css
/* nothing */
```

### Actual result
```css
.cssnano-test{display:block}
```
