### ISSUE TITLE
Merge Rules doesn't works

### ISSUE THREAD

**Issue by ashfahan** [cssnano/cssnano#805]
due to our work flow we have similar elements styles in different files with different properties currently we are using https://github.com/ChristianMurphy/postcss-combine-duplicated-selectors to merge them together

after Switching to css-nano they doesn't combine.

You can see how styles were combined before and after use of css nano on various styles like 
`body` `hr` `a` `legend` `h1`
[fluid-sanitize-plus.css history](https://github.com/fluid-framework/Fluid/commits/bc46dd829b419cd3c414b4dfa8168c1f41f26b59/dist/fluid-sanitize-plus.css)

are we missing something here ?

**Update**: Css nano doesn't merge the following code until `body, input` style is removed or moved ahead or behind the merge-able code

```
body {
  line-height: 1.5;
  -webkit-text-size-adjust: 100%;
  -webkit-tap-highlight-color: transparent;
}


body, input {
  margin: 0;
}

body {
  color: #474747;
  background-color: #f0f0f0;
  text-align: left;
  -moz-tab-size: 4;
    -o-tab-size: 4;
       tab-size: 4;
  font-family: -apple-system, blinkmacsystemfont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Ubuntu", "Cantarell", "Noto Sans", "Helvetica Neue", arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-weight: 400;
}
```

**Comment by evilebottnawi** [comment]
What output you expected?

**Comment by ashfahan** [comment]
Shouldn't the output have merge body into one style ?
correct me if i am wrong.
 
```
body {
  line-height: 1.5;
  -webkit-text-size-adjust: 100%;
  -webkit-tap-highlight-color: transparent;
  color: #474747;
  background-color: #f0f0f0;
  text-align: left;
  -moz-tab-size: 4;
    -o-tab-size: 4;
       tab-size: 4;
  font-family: -apple-system, blinkmacsystemfont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Ubuntu", "Cantarell", "Noto Sans", "Helvetica Neue", arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-weight: 400;
}

body, input {
  margin: 0;
}
```

**Comment by ben-eb** [comment]
@evilebottnawi I don't think there's a specific limitation with body, but the decision to merge adjacent rules only is because we don't know the DOM structure and so cannot make an informed decision about re-arranging styles. If we take some CSS:

```css
.a {
  color: red;
}

.b {
  color: blue;
}

.c {
  color: red;
}
```

And some HTML:

```
<div class="c b">Hi!</div>
```

This CSS would produce `red` text. However if we re-arrange to the top-most selector we would get this CSS which would produce `blue` instead, due to the cascade:

```css
.a, .c {
  color: red;
}

.b {
  color: blue;
}
```

I'm sure we have many more examples in the issue log but that's essentially the gist of it; we can't know more without knowing your DOM structure. This is where tools such as [CSS Blocks](https://css-blocks.com/) can produce an optimal stylesheet as they know which styles are being applied to which elements, and we can compress this after the fact.

**Comment by ashfahan** [comment]
@ben-eb your example is clear but code i have doesn't have duplicate properties but duplicate styles/class names.

my Issue is related to the merge styles/class names, not to merge properties.

merging styles/class names into one (in my case) won't cause any cascade issues.

if i further modify css nano merge rule [example](https://cssnano.co/optimisations/mergerules/) to this code.

```
.box {
  color: blue;
}

.circle{
  border-radius:50%;
}

.box {
  font-weight: 700;
  color: red;
  background: pink;
}
```

Expected:

```
.box {
    color: blue;
    background: pink;
    font-weight: 700;
    color: red;
}

.circle{
  border-radius:50%;
}
```

it would be optimal if css nano combine .box styles into one in the same cascade way they are written.
Note how color: red override color:blue in my expected result

**Comment by ben-eb** [comment]
True, it may be safe to merge non-adjacent selectors if there are no conflicting properties in the intermediary blocks. It may be difficult to do correctly however, given every "between" block exponentially increases the chances of a collision.

**Comment by ashfahan** [comment]
> True, it may be safe to merge non-adjacent selectors if there are no conflicting properties in the intermediary blocks.

if you are referring to duplicate properties having same value by that, e.g have same color property with same value we can safely remove then if they are in same selector 

> given every "between" block exponentially increases the chances of a collision.

I do agree with you

**Comment by xavierfoucrier** [comment]
Hi everyone,

My opinion about duplicate properties is that **CSS is made for cascading styles**: that's why we could safely **keep the last property** regarding the others.

This code:
```css
.selector {
  color: black;
}

.selector {
  border-radius: 5px;
  color: white;
}
```

Should result in:
```css
.selector {
  border-radius: 5px;
  color: white; // this is the last color property that is keep
}
```

I am working with `less` and got this issue, just with a simple `mixin`:

```less
.title-styleguide() {
  color: blue;
  font-size: 20px;
  text-transform: uppercase;
}

.h2 {
  .title-styleguide(); // apply title style guides
}

.h2-small {
  .title-styleguide();

  // this should override the previous styles (in fact is does in the browser)
  // but the previous font size is not removed from the compiled source
  font-size: 15px;
}
```

Nice compression took BTW :wink:

**Comment by mandolin** [comment]
@xavierfoucrier  I agree, I think this feature is important. Maybe an option named 'mergeSameRule'? Further redundancy removal than current 'discardDuplicates'.

**Comment by danielhaim1** [comment]
I wanted to chime in and say that I would greatly appreciate this feature, especially for multiple declarations such as:

**Before:**
```scss
:root {
  --white: #FFFFFF;
  --black: #000000;
}

:root{
 --base-font-family: Helvetica;
}
```

**Expected:**
```scss
:root {
  --white: #FFFFFF;
  --black: #000000;
  --base-font-family: Helvetica;
}
```
