### ISSUE TITLE
calc width PX doesn't work when I try to minify the CSS

### ISSUE THREAD

**Issue by imjeen** [cssnano/cssnano#811]
I have a  special CSS, see below. I don't want the **px** to translate **rem**, so that I use the **PX**  ( it 's a way to use a capital in the pixel unit declaration about [postcss-pxtorem](https://github.com/cuth/postcss-pxtorem#a-message-about-ignoring-properties) ) . And It cannot to minify the calc width PX.
```CSS
#content{
  /* some css */
  /* prettier-ignore */
   min-height: calc(100% + 1PX);
}
```

I found the related issue: https://github.com/cuth/postcss-pxtorem/issues/51.

## devDependencies

cssnano@4.1.10
