### ISSUE TITLE
Invalid minification of var() fallback

### ISSUE THREAD

**Issue by James0x57** [cssnano/cssnano#822]
**Playground Input:**
```css
div {
  border-radius: 10px var(--foobar, );
}
```

**Actual output**
```css
div{border-radius:10px var(--foobar,)}
```
(the empty fallback in var() is invalid and results in the whole rule being ignored. The space is required)

**Expected output**
```css
div{border-radius:10px var(--foobar, )}
```
(must have the space in the fallback value to be valid)

Could be an issue somewhere upstream in postcss - happy to submit a PR either way if someone familiar with the code bases could point me roughly near the code that would be responsible.
