### ISSUE TITLE
Merging rules is unsafe with all

### ISSUE THREAD

**Issue by stof** [cssnano/cssnano#824]
```css
.foo {
  color: red
}
.bar {
  all: unset;
  color:red
}
```

cssnano produces this output:

```
.bar,.foo{color:red}.bar{all:unset}
```

But this changes the styles for `.bar` because of `all` unsetting the color too.

Regarding merging, `all` should forbid *any* other rule (except `direction` and `unicode-bidi`) of this selector to move accross it.
https://developer.mozilla.org/en-US/docs/Web/CSS/all
