### ISSUE TITLE
Duplicate properties removed (for env - constant)

### ISSUE THREAD

**Issue by dorianrod** [cssnano/cssnano#846]
Hi,

This code:

.cls {
padding-top: 1rem;
padding-top: calc(1rem + constant(safe-area-inset-top));
padding-top: calc(1rem + env(safe-area-inset-top));
}

is reduced in:
.cls {
padding-top: calc(1rem + env(safe-area-inset-top));
}

the problem is that I need to keep these 3 properties because it depends on the environment (some supports constant or env, or none).

Is there a way / an option to keep all these properties?

Have a good day
DR

**Comment by anikethsaha** [comment]
It's a very weird use case cause anyway your browser will discard the top ones.
I don't think you can opt-out from this from the preset !

cc @evilebottnawi

**Comment by evilebottnawi** [comment]
It is bug, we should keep both of them because it can break code for legacy browsers

**Comment by anikethsaha** [comment]
```css
.cls {
padding-top: 1rem;
}
.cls {
padding-top: calc(1rem + constant(safe-area-inset-top));
}
.cls {
padding-top: calc(1rem + env(safe-area-inset-top));
}
```

What about this then? It will inject like this right

```css
.cls {
padding-top: 1rem;
padding-top: calc(1rem + constant(safe-area-inset-top));
padding-top: calc(1rem + env(safe-area-inset-top));
}
```

**Comment by evilebottnawi** [comment]
Keep them all

**Comment by anikethsaha** [comment]
I think a better fix for this will be to make the discard-duplicate plugin `opt-in-out`
like have an option in the preset to have enabled it or not
cause what this plugin mostly does is to remove those duplicates. if we are keeping them all, then it won't have many operations and use case to it

**Comment by evilebottnawi** [comment]
@anikethsaha it is unsafe minification, but plugins in safe preset so we should fix this unsafe case

**Comment by dorianrod** [comment]
> ```css
> .cls {
> padding-top: 1rem;
> }
> .cls {
> padding-top: calc(1rem + constant(safe-area-inset-top));
> }
> .cls {
> padding-top: calc(1rem + env(safe-area-inset-top));
> }
> ```
> 
> What about this then? It will inject like this right
> 
> ```css
> .cls {
> padding-top: 1rem;
> padding-top: calc(1rem + constant(safe-area-inset-top));
> padding-top: calc(1rem + env(safe-area-inset-top));
> }
> ```

Yes, it works as a temporary solution. But it implies to review all the css code to be sure that the css has not been changed after minification.

**Comment by Exelenz9** [comment]
Probably, a good solution here could be using the `@supports` media-query:

```css
.cls {
  padding-top: 1rem;
}

@supports (padding-top: constant(safe-area-inset-top)) {
  .cls {
    padding-top: calc(1rem + constant(safe-area-inset-top));
  }
}

@supports (padding-top: env(safe-area-inset-top)) {
  .cls {
    padding-top: calc(1rem + env(safe-area-inset-top));
  }
}
```

Such method worked for my case.
