### ISSUE TITLE
Combination of border and border-color results in wrong border

### ISSUE THREAD

**Issue by SveLil** [cssnano/cssnano#864]
The following css:

```css
.test {
  border: 3px solid transparent;
  border-color: inherit;
  border-bottom-color: transparent;
}
```

will produce the following output:
```css
test{border:3px solid transparent}
```

`mergeLonghand: false` did solve the issue

**Comment by anikethsaha** [comment]
whats the expected output?

it looks good to me,

the default value for CSS color I guess is `inherit` in max browsers.

**Comment by SveLil** [comment]
The problem comes into play, when you have cascading classes. The border-color: inherit is missing for the top, left and right border. So if the parent class defines a red color, the border for the test div should have a 3px solid red border on three sides and a transparent on the bottom.

See: https://codepen.io/svelil/pen/mdygaMb

**Comment by anikethsaha** [comment]
> The problem comes into play, when you have cascading classes. The border-color: inherit is missing for the top, left and right border. So if the parent class defines a red color, the border for the test div should have a 3px solid red border on three sides and a transparent on the bottom.
> 
> See: https://codepen.io/svelil/pen/mdygaMb

Thanks for the explanation, its a bug 
One fix can be to consider `inherit` as color too and do the merging accordingly

**Comment by t0f3rchr15** [comment]
Not sure if this is the same bug, but a simple merge of `border-width`, `border-style`, and `border-color`, like below, will result in an invalid shorthand border property:

input:
```css
.invalid-transformation {
  border-width: inherit;
  border-color: inherit;
  border-style: solid;
}
```

result:
```css
.invalid-transformation{border:inherit solid;border-color: inherit}
```

Changing `border-style`: to `inherit` or removing any one of these properties seems to clear the issue.

**Comment by nex3** [comment]
I'm seeing similar issues with the following CSS:

```css
a {
  border-color: inherit;
  border-style: inherit;
  border-width: inherit;
  border-width: 0;
}
```

This is producing:

```css
a {
  border: 0 inherit;
  border-color: inherit;
  border-width: inherit;
}
```

Note that there are actually two bugs with this output:

1. `border: 0 inherit` is invalid (as @t0f3rchr15 mentioned).
2. `border-width: inherit` isn't deleted, despite being overridden in the original CSS by `border-width: 0`, and in fact would override the 0 width even if bug 1 was fixed.

**Comment by hubgit** [comment]
I think this might be another example of the same issue:

```css
.parent {
    border: 1px solid orange;
}

.parent .child {
    border-width: 1px;
    border-style: solid;
    border-color: transparent;
    border-right-color: inherit;
    border-top-color: transparent;
    border-bottom-color: transparent;
}
```

gets minified to this, losing the `border-right-color: inherit`:

```
.parent{border:1px solid orange}.parent .child{border:1px solid transparent}
```

[open in playground](https://cssnano.co/playground/#eyJpbnB1dCI6Ii5wYXJlbnQge1xuICBib3JkZXI6IDFweCBzb2xpZCBvcmFuZ2U7XG59XG5cbi5wYXJlbnQgLmNoaWxkIHtcbiAgICBib3JkZXItd2lkdGg6IDFweDtcbiAgICBib3JkZXItc3R5bGU6IHNvbGlkO1xuICAgIGJvcmRlci1jb2xvcjogdHJhbnNwYXJlbnQ7XG4gICAgYm9yZGVyLXJpZ2h0LWNvbG9yOiBpbmhlcml0O1xuICAgIGJvcmRlci10b3AtY29sb3I6IHRyYW5zcGFyZW50O1xuICAgIGJvcmRlci1ib3R0b20tY29sb3I6IHRyYW5zcGFyZW50O1xufVxuIiwiY29uZmlnIjoiY3NzbmFuby1wcmVzZXQtZGVmYXVsdCJ9)
