### ISSUE TITLE
Template string variables removed when using with Next.js and styled-jsx

### ISSUE THREAD

**Issue by cullylarson** [cssnano/cssnano#885]
I'm using `postcss` with `styled-jsx`. `postcss` processes the style and sends it to styled-jsx to embed in the page. `styled-jsx` allows using javascript variables in styles. The problem is that for some reason `cssnano` is removing variables in JS templates strings.

For example, if I provide this:

```css
<style jsx>
    {`
        .categories {
            --numColumns: ${numColumns.xl};
            --gapWidth: 20px;

            padding-left: 10px;
            overflow-x: hidden;
        }
    }`
</style>
```

It will produce something like:

```css
.categories {
    --gapWidth: 20px;

    padding-left: 10px;
    overflow-x: hidden;
}
```

I did notice that if I wrap the variable in quotes, it isn't removed (e.g. `--numColumns: "${numColumns.xl}";` produces `--numColumns: "5"`). However, I need the variable to be a number and the browser doesn't treat it as such if it's in quotes.

If I remove `cssnano` from my plugins list, the problem goes away. I've tried turning off all of the `cssnano` options and the problem persists. Any idea why this would happen and how it could be fixed?

Btw, this is how I attempted to disable all of the `cssnano` options (in `postcss.config.js`):

```
'cssnano': {
    zindex: false,
    autoprefixer: false,
    discardComments: {removeAll: true},
    cssDeclarationSorter: false,
    rawCache: false,
    calc: false,
    colormin: false,
    convertValues: false,
    discardDuplicates: false,
    discardEmpty: false,
    discardOverridden: false,
    discardUnused: false,
    mergeIdents: false,
    mergeLonghand: false,
    mergeRules: false,
    minifyFontValues: false,
    minifyGradients: false,
    minifyParams: false,
    minifySelectors: false,
    normalizeCharset: false,
    normalizeDisplayValues: false,
    normalizePositions: false,
    normalizeRepeatStyle: false,
    normalizeString: false,
    normalizeTimingFunctions: false,
    normalizeUnicode: false,
    normalizeUrl: false,
    normalizeWhitespace: false,
    orderedValues: false,
    reduceIdents: false,
    reduceInitial: false,
    reduceTransforms: false,
    svgo: false,
    uniqueSelectors: false,
},
```
