### ISSUE TITLE
Improve gradient shortening.

### ISSUE THREAD

**Issue by ben-eb** [cssnano/cssnano#887]
We should be able to handle these two cases:

https://twitter.com/stefanjudis/status/1239488340682039297

```css
div {
  background: linear-gradient(
    #fc6262 20%, 
    #50bbf6 20% 40%, 
    #aaffef 40% 60%, 
    #f9e699 60% 80%, 
    #2c3749 80%
  )
}
```

Currently converts to:

```css
div {
  background: linear-gradient(
    #fc6262 20%, 
    #50bbf6 0 40%, 
    #aaffef 40% 60%, 
    #f9e699 60% 80%, 
    #2c3749 80%
  )
}
```

When it could convert to:

```css
div {
  background: linear-gradient(
    #fc6262 20%, 
    #50bbf6 0 40%, 
    #aaffef 0 60%, 
    #f9e699 0 80%, 
    #2c3749 0
  )
}
```

In addition, we could add support for conic gradients.
