### ISSUE TITLE
border-x-x-radius don’t combine into the border-radius shorthand

### ISSUE THREAD

**Issue by brookjordan** [cssnano/cssnano#890]
The following:
```css
.box {
  border-top-left-radius: 10px;
  border-top-right-radius: 20px;
  border-bottom-left-radius: 20px;
  border-bottom-right-radius: 40px;
}
```

is currently minified to:
```css
.box{border-top-left-radius:10px;border-top-right-radius:20px;border-bottom-left-radius:20px;border-bottom-right-radius:40px}
```

but could be “short-hand”ed:
```css
.box {border-radius: 10px 20px 40px}
```

**Comment by brookjordan** [comment]
To expand upon that, this:
```css
.box {
  border-radius: 20px;
  border-top-left-radius: 10px 30px;
  border-bottom-right-radius: 10px 40px;
}
```
is currently minified to:
```css
.box{border-radius:20px;border-top-left-radius:10px 30px;border-bottom-right-radius:10px 40px}
```
and could be taken down to:
```css
.box{border-radius:10px 20px/30px 20px 40px;}
```
