### ISSUE TITLE
[Bug] : broken declarations due to unitless 0 inside `max()`

### ISSUE THREAD

**Issue by hacknug** [cssnano/cssnano#900]
**Describe the bug**
`cssnano` is messing with 0-like values inside `max()` (most likely `min()` and `clamp()` too).

> Note: Because `<number-token>`s are always interpreted as `<number>`s or `<integer>`s, "unitless 0" `<length>`s aren’t supported in math functions. That is, width: calc(0 + 5px); is invalid, because it’s trying to add a `<number>` to a `<length>`, even though both width: 0; and width: 5px; are valid.

**To Reproduce**

1. Open the playground on a new tab https://cssnano.co/playground/
2. Paste the following code
```css
/* Your CSS here */
.invalid_pb-0-safe { padding-bottom: max(0, env(safe-area-inset-bottom)); }
.valid_broken_1_pb-0-safe { padding-bottom: max(0px, env(safe-area-inset-bottom)); }
.valid_broken_2_pb-0-safe { padding-bottom: max(calc(0 * 1px), env(safe-area-inset-bottom)); }
.valid_working_pb-0-safe { padding-bottom: max(0 * 1px, env(safe-area-inset-bottom)); }
```

**Expected behavior**
- `.invalid_pb-0-safe`: invalid because it contains unitless values. Can be dropped
- `.valid_broken_1_pb-0-safe`: valid because it doesn't contain unitless values. Should be kept untouched
- `.valid_broken_2_pb-0-safe`: valid because it doesn't contain unitless values. Should be kept although it might be better to compute and keep as `0px`
- `.valid_working_pb-0-safe`: valid and currently the only way to prevent cssnano from messing with it (?). Should be kept as is (already working, no need to change anything for this one)

**Screenshots**
If applicable, add screenshots to help explain your problem. (from [cssnano-playground](https://cssnano.co/playground/))

**Desktop (please complete the following information):**
- Whatever the playground is using.

**Additional context**
Revelant links to the spec:
- https://drafts.csswg.org/css-values-4/#comp-func
- https://drafts.csswg.org/css-values-4/#calc-type-checking

Encountered the issue when testing for a patch for this other project here: https://github.com/desaintflorent/tailwindcss-padding-safe/issues/1
