### ISSUE TITLE
[Feature Request] Add css var removal to discardUnused postcss-discard-unused

### ISSUE THREAD

**Issue by dmnsgn** [cssnano/cssnano#911]
**Is your feature request related to a problem? Please describe.**
I sometimes include "libraries" declaring a bunch of css variables in the `:root`. When compiling with css nano, they end up in the bundle even though they are not used.

**Describe the solution you'd like**

I see two solutions to this issue:
- extend `discardUnused` to take care of those var(--my-var) not found in the rest of the file
- add a separate `discardUnusedVariables` optimisation with default `unsafe`

It is an unsafe transform because un-used variables from :root can be used in other stylesheets on a website but if you only have one stylesheet and you know this is a problem, you'd definetely want to get rid of these extra lines of code.

**Additional context**

Some prior work seems to be done here: https://github.com/Plugin-contrib/postcss-unused-var

Not sure why it has been archived and if there are concern using this approach.

**Are you willing to work on this ?**

I could but it looks like it is a matter of moving postcss-unused-var here?

**Comment by evilebottnawi** [comment]
Removing CSS variables is not safe, we try to avoid all unsafe actions

**Comment by anikethsaha** [comment]
Thanks for the issue. 

As mentioned by @evilebottnawi , CSS variables are hoisted across CSS files as well. 
and those which are declared in `declaration` like `h1{--var1: red}`, this `var1` can be used outside as well. 
That was the reason for archiving `postcss-unused-var` cause it can lead to un-safe transformation.

**Comment by dmnsgn** [comment]
I don't know what is exactly cssnano policy in re unsafe transform but I see there are currently 4 available: discardunused, mergeidents, reduceidents and zindex. Assuming users that opt in for  unsafe transforms know what they are doing, would this behaviour still be _too_ unsafe for cssnano?

**Comment by anikethsaha** [comment]
Removal of css variables can be un-safe as they are hoisted.

`postcss-unused-vars` was doing the following thing

Input

```css
a {
  --var1: red;
  --var2: green;
  color: var(--var1);
}
```
⬇️ 

Output

```css
a {
  --var1: red;
  color: var(--var1);
}
```

But `var2` could be used like this as well 

```css
a {
  --var1: red;
  --var2: green;
  color: var(--var1);
}

p{
     color: var(--var2);
}
```

This will be transformed to 

```css
a {
  --var1: red;
  color: var(--var1);
}

p{
     color: var(--var2);
}
```


This is un-safe.
