### ISSUE TITLE
[Bug] : postcss-minify-gradients crashes when using custom CSS properties

### ISSUE THREAD

**Issue by AckmanDESU** [cssnano/cssnano#914]
**Describe the bug**
I created a class which adds a gradient. The gradient's direction depends on a custom property. Compiling the code crashes cssnano.

**To Reproduce**
My code:

```css
.box--has-overlay {
    background-image: linear-gradient(
        to var(--box-position),
        white,
        black
    );
}
```

**Expected behavior**
The code should compile without crashing

**Desktop (please complete the following information):**
- CSSNANO Version 4.1.10
- Add the output of `npx envinfo && npm ls cssnano` here

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 3.73 GB / 15.93 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Composer: 1.9.0 - C:\ProgramData\ComposerSetup\bin\composer.BAT       
  Utilities:
    Git: 2.23.0. - /mingw64/bin/git
    Clang: 9.0.0 - C:\Users\user\scoop\shims\clang.EXE
  Virtualization:
    VirtualBox: 6.0.12 - C:\Program Files\Oracle\VirtualBox\vboxmanage.EXE
  IDEs:
    VSCode: 1.45.0 - C:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
    Perl: 5.26.2 - C:\Program Files\Git\usr\bin\perl.EXE
    PHP: 7.3.10 - C:\tools\php73\php.EXE
  Databases:
    MySQL: undefined - C:\tools\mysql\current\bin\mysql.EXE
  Browsers:
    Edge: 44.18362.449.0
    Internet Explorer: 11.0.18362.1
```

**Comment by anikethsaha** [comment]
Thanks for the report. 


Having css variables in gradients wont be optimized. 
as it will return from [here](https://github.com/cssnano/cssnano/tree/master/packages/https://github.com/cssnano/cssnano/blob/master/packages/postcss-minify-gradients/src/index.js#L29)

This crashing issue has been fixed already and it will be shipped with next release.

**Comment by CarterLi** [comment]
Encountered this issue. When will the next release be actually released?

**Comment by ludofischer** [comment]
Solved in latest 5.0.0 release. The example minimizes without crashing to:

```css
.box--has-overlay{background-image:linear-gradient(to var(--box-position),#fff,#000)}
```
