### ISSUE TITLE
[Bug] `:focus-visible` still merged and breaks the CSS

### ISSUE THREAD

**Issue by johanvanhelden** [cssnano/cssnano#932]
`:focus-visible` classes are merged. This breaks the CSS.

I've noticed that this issue should have been fixed in March in https://github.com/cssnano/cssnano/pull/882, but for some reason it is still merging them.

In my un-minified source CSS I have the following, working, TailwindCSS code:

```css
.focus-visible\:underline.focus-visible {
  text-decoration: underline;
}

.focus-visible\:underline:focus-visible {
  text-decoration: underline;
}
```

After running cssnano I get the following, broken, code:
```css
.focus-visible\:underline.focus-visible,.focus-visible\:underline:focus-visible{text-decoration:underline}
```

The result is that my focus visible classes no longer trigger. The merge breaks the CSS.

**To Reproduce**
1. Go to https://cssnano.co/playground/
2. Paste my un-minified CSS example
3. Notice on the right side the rules are merged.

To notice how this breaks the CSS:
1. Go to https://codepen.io/johanvanhelden/pen/GRoVZXr
2. See everything is working, the middle link is underlined. 
3. Switch the un-minified CSS for the minified CSS and see the underline is no longer working.

**Expected behavior**
The `:focus-visible` classes should remain stand-alone. To prevent the polyfill classes from breaking.

**Desktop**
```
└─┬ laravel-mix@5.0.4
  └─┬ optimize-css-assets-webpack-plugin@5.0.3
    └─┬ cssnano@4.1.10
      └─┬ cssnano-preset-default@4.0.7
        └── postcss-merge-rules@4.0.3 
```
