### ISSUE TITLE
postcss-merge-longhand not modifying output in browser

### ISSUE THREAD

**Issue by markthomasmiller** [cssnano/cssnano#950]
When run in the browser, postcss-merge-longhand doesn't transform the output. I'm trying this with the [sample string](https://www.npmjs.com/package/postcss-merge-longhand#example) from your documentation; my use case is very similar. If there's additional setup necessary to make this work in the browser, I'd be happy to contribute an update to the docs.

## Input

```css
h1 {
  margin-top: 10px;
  margin-right: 20px;
  margin-bottom: 10px;
  margin-left: 20px;
}
```

## Expected output

```css
h1 {
  margin: 10px 20px;
}
```

## Actual output

```css
h1 {
  margin-top: 10px;
  margin-right: 20px;
  margin-bottom: 10px;
  margin-left: 20px;
}
```

## Code

```js
import postcss from 'postcss-js'
import mergeLonghand from 'postcss-merge-longhand'

const merge = postcss.sync([mergeLonghand])

const string = `h1 {
  margin-top: 10px;
  margin-right: 20px;
  margin-bottom: 10px;
  margin-left: 20px;
}`

const merged = merge({ string })

console.log(merged.string)
```
