### ISSUE TITLE
[Bug] : Wrong shorten border declaration with custom properties

### ISSUE THREAD

**Issue by raphaelthanner** [cssnano/cssnano#965]
Source:

```css
:root {
    --border-width: 2px 4px;
    --border-style: solid;
    --border-color: #000;
}

.element {
    border-width: var(--border-width);
    border-style: var(--border-style);
    border-color: var(--border-color);
}
```

Output:

```css
:root {
    --border-width: 2px 4px;
    --border-style: solid;
    --border-color: #000
}

.element {
    border: var(--border-width) var(--border-style) var(--border-color)
    /* "border: 2px 4px solid #000" is not valid */
}
```
