### ISSUE TITLE
[Bug] : merge rules bug when use @supports

### ISSUE THREAD

**Issue by edokeh** [cssnano/cssnano#974]
**Describe the bug**

cssnano not working correctly  when use @supports 

**To Reproduce**

origin css

```css
@media  only screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2),  only screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 2) {
  @supports (padding-bottom: constant(safe-area-inset-bottom)) {
    .test {
      padding-bottom: calc(2 * constant(safe-area-inset-bottom));
    }
  }
}
@media  only screen and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3),  only screen and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3),  only screen and (device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3),  only screen and (device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) {
  @supports (padding-bottom: constant(safe-area-inset-bottom)) {
    .test {
      padding-bottom: calc(3 * constant(safe-area-inset-bottom));
    }
  }
}
```

**Wrong output with cssnano**

```js
@media only screen and (device-width:375px) and (device-height:812px) and (-webkit-device-pixel-ratio:2),only screen and (device-width:414px) and (device-height:896px) and (-webkit-device-pixel-ratio:2){@supports (padding-bottom:constant(safe-area-inset-bottom)){.test{padding-bottom:calc(2*constant(safe-area-inset-bottom));padding-bottom:calc(3*constant(safe-area-inset-bottom))}}}
```
